// Builds a single self-contained migration for environments where we cannot
// run the node loader, e.g. pasting into the Railway SQL editor.
//
//   node backend/migrate_production_quiz.js
//
// Emits backend/migrate_production_quiz.sql. The output is idempotent: running
// it twice leaves the same row counts.
const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

const CSV_DIR = path.join(__dirname, 'seed_questions');
const OUT = path.join(CSV_DIR, 'migrate_production_quiz.sql');
const LETTERS = ['A', 'B', 'C', 'D'];

// Subjects seeded before their questions, in the order they are inserted.
const SUBJECTS = [
  { code: 'ENG201', name: 'English Language', className: 'SSS 1' },
  { code: 'MTH201', name: 'Mathematics',      className: 'SSS 1' },
  { code: 'PHY201', name: 'Physics',          className: 'SSS 1' },
  { code: 'CHM201', name: 'Chemistry',        className: 'SSS 1' }
];

// Escapes for a single quoted MySQL string literal.
function sqlString(value) {
  return "'" + String(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "''") + "'";
}

function readCsv(file) {
  const wb = XLSX.readFile(path.join(CSV_DIR, file), { raw: true });
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { raw: true, defval: '' });
  const codes = [...new Set(rows.map(r => String(r['Subject Code'] || '').trim()).filter(Boolean))];
  if (codes.length !== 1) {
    console.log('  ' + file + ': expected one Subject Code, found ' + codes.length + ' - skipped');
    return null;
  }
  const out = [];
  const skipped = [];
  rows.forEach((r, i) => {
    const text = String(r['Question'] || '').trim();
    const opts = ['Option A', 'Option B', 'Option C', 'Option D'].map(k => String(r[k] || '').trim());
    const key = String(r['Correct Option'] || '').trim().toUpperCase();
    if (!text || opts.some(o => !o) || new Set(opts.map(o => o.toLowerCase())).size !== 4
        || !LETTERS.includes(key)) {
      skipped.push(file + ' row ' + (i + 2));
      return;
    }
    out.push({ text, opts, key });
  });
  if (skipped.length) console.log('  ' + file + ': skipped invalid ' + skipped.join(', '));
  return { code: codes[0], rows: out };
}

const files = fs.readdirSync(CSV_DIR).filter(f => /^SSS1_.*\.csv$/.test(f)).sort();
if (!files.length) {
  console.error('No SSS1_*.csv files found in ' + CSV_DIR);
  process.exit(1);
}

const loaded = {};
for (const f of files) {
  const parsed = readCsv(f);
  if (!parsed) continue;
  const subject = SUBJECTS.find(s => s.code === parsed.code);
  if (!subject) {
    console.log('  ' + f + ': subject code ' + parsed.code + ' is not one of the four, skipped');
    continue;
  }
  loaded[subject.code] = parsed.rows;
  console.log('  ' + f + ' -> ' + subject.code + ' (' + parsed.rows.length + ' questions)');
}

const missing = SUBJECTS.filter(s => !loaded[s.code]);
if (missing.length) {
  console.error('No questions for: ' + missing.map(s => s.code).join(', '));
  process.exit(1);
}

const L = [];
const totalRows = Object.values(loaded).reduce((n, r) => n + r.length, 0);

L.push('-- ============================================================');
L.push('-- FREPPA quiz migration: SSS 1 English, Mathematics,');
L.push('-- Physics and Chemistry.');
L.push('--');
L.push('-- Generated by backend/migrate_production_quiz.js');
L.push('-- Contains ' + totalRows + ' questions across ' + SUBJECTS.length + ' subjects.');
L.push('--');
L.push('-- Safe to run more than once. Each step is guarded, so running');
L.push('-- this twice does not duplicate subjects or questions.');
L.push('--');
L.push('--   mysql -u USER -p DBNAME < backend/migrate_production_quiz.sql');
L.push('--');
L.push('-- Or paste the whole file into the Railway SQL editor.');
L.push('-- ============================================================');
L.push('');
L.push('SET NAMES utf8mb4;');
L.push('');
L.push('-- ------------------------------------------------------------');
L.push('-- 1. Questions table');
L.push('-- ------------------------------------------------------------');
L.push('');
L.push('CREATE TABLE IF NOT EXISTS questions (');
L.push('    id INT AUTO_INCREMENT PRIMARY KEY,');
L.push('    subject_id INT NOT NULL,');
L.push('    question_text TEXT NOT NULL,');
L.push('    option_a VARCHAR(255) NOT NULL,');
L.push('    option_b VARCHAR(255) NOT NULL,');
L.push('    option_c VARCHAR(255) NOT NULL,');
L.push('    option_d VARCHAR(255) NOT NULL,');
L.push('    correct_option ENUM(\'A\',\'B\',\'C\',\'D\') NOT NULL,');
L.push('    is_active TINYINT(1) NOT NULL DEFAULT 1,');
L.push('    created_by INT,');
L.push('    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,');
L.push('    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,');
L.push('    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,');
L.push('    INDEX idx_questions_subject (subject_id, is_active)');
L.push(') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;');
L.push('');

SUBJECTS.forEach((s, i) => {
  L.push('-- ------------------------------------------------------------');
  L.push('-- ' + (i + 2) + '. Subject: ' + s.name + ' (' + s.code + ')');
  L.push('-- ------------------------------------------------------------');
  L.push('');
  L.push('-- subjects.subject_code is UNIQUE, so IGNORE skips it if present.');
  L.push('-- teacher_id is left NULL: the student quiz list only requires a');
  L.push('-- subject in the student\'s own class that has questions.');
  L.push('INSERT IGNORE INTO subjects (subject_name, subject_code, class_id, teacher_id)');
  L.push('SELECT ' + sqlString(s.name) + ', ' + sqlString(s.code) + ', c.id, NULL');
  L.push('  FROM classes c');
  L.push(' WHERE c.class_name = ' + sqlString(s.className) + ';');
  L.push('');
});

SUBJECTS.forEach((s, i) => {
  const rows = loaded[s.code];
  L.push('-- ------------------------------------------------------------');
  L.push('-- ' + (i + 3 + SUBJECTS.length) + '. Questions for ' + s.code + ' (' + rows.length + ')');
  L.push('-- ------------------------------------------------------------');
  L.push('');
  L.push('-- The NOT EXISTS guard means a subject that already has questions');
  L.push('-- is left untouched, so a re-run cannot duplicate the pool.');
  L.push('INSERT INTO questions');
  L.push('    (subject_id, question_text, option_a, option_b, option_c, option_d, correct_option)');
  L.push('SELECT s.id, t.q, t.a, t.b, t.c, t.d, t.k');
  L.push('  FROM subjects s');
  L.push('  JOIN (');
  rows.forEach((r, j) => {
    const prefix = j === 0 ? '    SELECT ' : '    UNION ALL SELECT ';
    L.push(prefix + sqlString(r.text) + ' AS q, '
      + sqlString(r.opts[0]) + ' AS a, '
      + sqlString(r.opts[1]) + ' AS b, '
      + sqlString(r.opts[2]) + ' AS c, '
      + sqlString(r.opts[3]) + ' AS d, '
      + sqlString(r.key) + ' AS k');
  });
  L.push('  ) t ON 1 = 1');
  L.push(' WHERE s.subject_code = ' + sqlString(s.code));
  L.push('   AND NOT EXISTS (SELECT 1 FROM questions x WHERE x.subject_id = s.id);');
  L.push('');
});

L.push('-- ------------------------------------------------------------');
L.push('-- Verification: expect 4 subjects and ' + totalRows + ' questions.');
L.push('-- Verification: expect 4 subjects and ' + totalRows + ' questions.');
L.push('SELECT s.subject_code, s.subject_name, COUNT(q.id) AS questions');
L.push('  FROM subjects s');
L.push('  LEFT JOIN questions q ON q.subject_id = s.id AND q.is_active = 1');
L.push(" WHERE s.subject_code IN ('ENG201','MTH201','PHY201','CHM201')");
L.push(' GROUP BY s.id, s.subject_code, s.subject_name');
L.push(' ORDER BY s.subject_code;');
L.push('');
L.push('SELECT COUNT(*) AS total_questions FROM questions;');
L.push('');

fs.writeFileSync(OUT, L.join('\n'), 'utf8');
console.log('\nWrote ' + OUT);
console.log('  ' + totalRows + ' questions, ' + L.length + ' lines, '
  + (fs.statSync(OUT).size / 1024).toFixed(1) + ' KB');
