-- ============================================================
-- FREPPA quiz migration: SSS 1 English, Mathematics,
-- Physics and Chemistry.
--
-- Generated by backend/migrate_production_quiz.js
-- Contains 497 questions across 4 subjects.
--
-- Safe to run more than once. Each step is guarded, so running
-- this twice does not duplicate subjects or questions.
--
--   mysql -u USER -p DBNAME < backend/migrate_production_quiz.sql
--
-- Or paste the whole file into the Railway SQL editor.
-- ============================================================

SET NAMES utf8mb4;

-- ------------------------------------------------------------
-- 1. Questions table
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject_id INT NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_option ENUM('A','B','C','D') NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_questions_subject (subject_id, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- 2. Subject: English Language (ENG201)
-- ------------------------------------------------------------

-- subjects.subject_code is UNIQUE, so IGNORE skips it if present.
-- teacher_id is left NULL: the student quiz list only requires a
-- subject in the student's own class that has questions.
INSERT IGNORE INTO subjects (subject_name, subject_code, class_id, teacher_id)
SELECT 'English Language', 'ENG201', c.id, NULL
  FROM classes c
 WHERE c.class_name = 'SSS 1';

-- ------------------------------------------------------------
-- 3. Subject: Mathematics (MTH201)
-- ------------------------------------------------------------

-- subjects.subject_code is UNIQUE, so IGNORE skips it if present.
-- teacher_id is left NULL: the student quiz list only requires a
-- subject in the student's own class that has questions.
INSERT IGNORE INTO subjects (subject_name, subject_code, class_id, teacher_id)
SELECT 'Mathematics', 'MTH201', c.id, NULL
  FROM classes c
 WHERE c.class_name = 'SSS 1';

-- ------------------------------------------------------------
-- 4. Subject: Physics (PHY201)
-- ------------------------------------------------------------

-- subjects.subject_code is UNIQUE, so IGNORE skips it if present.
-- teacher_id is left NULL: the student quiz list only requires a
-- subject in the student's own class that has questions.
INSERT IGNORE INTO subjects (subject_name, subject_code, class_id, teacher_id)
SELECT 'Physics', 'PHY201', c.id, NULL
  FROM classes c
 WHERE c.class_name = 'SSS 1';

-- ------------------------------------------------------------
-- 5. Subject: Chemistry (CHM201)
-- ------------------------------------------------------------

-- subjects.subject_code is UNIQUE, so IGNORE skips it if present.
-- teacher_id is left NULL: the student quiz list only requires a
-- subject in the student's own class that has questions.
INSERT IGNORE INTO subjects (subject_name, subject_code, class_id, teacher_id)
SELECT 'Chemistry', 'CHM201', c.id, NULL
  FROM classes c
 WHERE c.class_name = 'SSS 1';

-- ------------------------------------------------------------
-- 7. Questions for ENG201 (104)
-- ------------------------------------------------------------

-- The NOT EXISTS guard means a subject that already has questions
-- is left untouched, so a re-run cannot duplicate the pool.
INSERT INTO questions
    (subject_id, question_text, option_a, option_b, option_c, option_d, correct_option)
SELECT s.id, t.q, t.a, t.b, t.c, t.d, t.k
  FROM subjects s
  JOIN (
    SELECT 'Which of the following is an abstract noun?' AS q, 'Table' AS a, 'Honesty' AS b, 'River' AS c, 'Teacher' AS d, 'B' AS k
    UNION ALL SELECT 'In the sentence ''She closed the door quietly'', the word ''quietly'' is a(n)' AS q, 'conjunction' AS a, 'adjective' AS b, 'adverb' AS c, 'noun' AS d, 'C' AS k
    UNION ALL SELECT 'Which of the following is a collective noun?' AS q, 'Crowd' AS a, 'Flock' AS b, 'Herd' AS c, 'Committee' AS d, 'A' AS k
    UNION ALL SELECT 'The word ''Wow'' in ''Wow, that was amazing!'' is a(n)' AS q, 'pronoun' AS a, 'conjunction' AS b, 'adverb' AS c, 'interjection' AS d, 'D' AS k
    UNION ALL SELECT 'Which of the following is a pronoun?' AS q, 'Beauty' AS a, 'Quickly' AS b, 'Under' AS c, 'She' AS d, 'D' AS k
    UNION ALL SELECT 'In ''The patient nurse attended to him'', the word ''patient'' is a(n)' AS q, 'noun' AS a, 'conjunction' AS b, 'adverb' AS c, 'adjective' AS d, 'D' AS k
    UNION ALL SELECT 'Which of the following is a preposition?' AS q, 'Between' AS a, 'Although' AS b, 'Beautiful' AS c, 'Quickly' AS d, 'A' AS k
    UNION ALL SELECT 'The word ''Although'' in ''Although it rained, we still went out'' is a' AS q, 'pronoun' AS a, 'preposition' AS b, 'conjunction' AS c, 'adverb' AS d, 'C' AS k
    UNION ALL SELECT 'Which of the following is a proper noun?' AS q, 'City' AS a, 'River' AS b, 'Chair' AS c, 'Lagos' AS d, 'D' AS k
    UNION ALL SELECT 'In ''We visited Abeokuta last month'', the word ''Abeokuta'' is a' AS q, 'common noun' AS a, 'proper noun' AS b, 'collective noun' AS c, 'abstract noun' AS d, 'B' AS k
    UNION ALL SELECT 'Which of the following nouns is concrete?' AS q, 'Courage' AS a, 'Table' AS b, 'Love' AS c, 'Honesty' AS d, 'B' AS k
    UNION ALL SELECT '''Bread'' in ''We were given some bread and milk'' is used as a' AS q, 'collective noun' AS a, 'abstract noun' AS b, 'count noun' AS c, 'mass noun' AS d, 'D' AS k
    UNION ALL SELECT 'Which of the following sentences is exclamatory?' AS q, 'What a beautiful dress!' AS a, 'Where are you going?' AS b, 'Please sit down.' AS c, 'The bell has rung.' AS d, 'A' AS k
    UNION ALL SELECT '''Kindly close the window.'' This sentence is a/an' AS q, 'exclamatory' AS a, 'interrogative' AS b, 'declarative' AS c, 'imperative' AS d, 'D' AS k
    UNION ALL SELECT '''The sun rises in the east.'' This sentence is' AS q, 'declarative' AS a, 'interrogative' AS b, 'imperative' AS c, 'exclamatory' AS d, 'A' AS k
    UNION ALL SELECT 'Which of the following is a simple sentence?' AS q, 'When I arrived, he had left.' AS a, 'She smiled and waved goodbye.' AS b, 'Because it rained, we stayed inside.' AS c, 'The boy ran very fast.' AS d, 'D' AS k
    UNION ALL SELECT '''Because it was raining, we stayed inside.'' This sentence is' AS q, 'complex' AS a, 'simple' AS b, 'compound' AS c, 'compound-complex' AS d, 'A' AS k
    UNION ALL SELECT '''I came and I saw him.'' This sentence is' AS q, 'compound' AS a, 'complex' AS b, 'compound-complex' AS c, 'simple' AS d, 'A' AS k
    UNION ALL SELECT '''When the bell rang, we left and she remained behind.'' This sentence is' AS q, 'simple' AS a, 'compound' AS b, 'compound-complex' AS c, 'complex' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''Each of the boys ___ a bag.''' AS q, 'has' AS a, 'were' AS b, 'have' AS c, 'are' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''Neither the teacher nor the students ___ present.''' AS q, 'is' AS a, 'are' AS b, 'was' AS c, 'were' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''The list of items ___ on the desk.''' AS q, 'is' AS a, 'are' AS b, 'were' AS c, 'have' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''Mathematics ___ my favourite subject.''' AS q, 'are' AS a, 'were' AS b, 'is' AS c, 'have' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''Ten thousand naira ___ a lot of money.''' AS q, 'is' AS a, 'were' AS b, 'have' AS c, 'are' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''Everyone ___ to school on foot.''' AS q, 'come' AS a, 'are coming' AS b, 'were coming' AS c, 'comes' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''She ___ to school every day.''' AS q, 'future simple' AS a, 'present simple' AS b, 'present continuous' AS c, 'past simple' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''Look! The children ___ in the garden.''' AS q, 'are studying' AS a, 'study' AS b, 'studied' AS c, 'will study' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''We ___ to Osogbo last year.''' AS q, 'have travelled' AS a, 'are travelling' AS b, 'travelled' AS c, 'will travel' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''She ___ when I called her on the phone.''' AS q, 'is cooking' AS a, 'was cooking' AS b, 'has cooked' AS c, 'will cook' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''I ___ my homework already.''' AS q, 'was finishing' AS a, 'will finish' AS b, 'have finished' AS c, 'am finishing' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''He ___ for the bus since morning.''' AS q, 'is waiting' AS a, 'has been waiting' AS b, 'waited' AS c, 'was waiting' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''By the time he arrived, the film ___.''' AS q, 'was starting' AS a, 'started' AS b, 'has started' AS c, 'had started' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''He usually ___ early for school.''' AS q, 'comes' AS a, 'will come' AS b, 'came' AS c, 'is come' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''She is a(n) ___ honest girl.''' AS q, 'a' AS a, 'the' AS b, 'no article' AS c, 'an' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''We did not go to church on ___ Monday.''' AS q, 'an' AS a, 'a' AS b, 'the' AS c, 'no article' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''I have been waiting ___ two hours.''' AS q, 'from' AS a, 'during' AS b, 'for' AS c, 'since' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''The key is ___ the table.''' AS q, 'in' AS a, 'on' AS b, 'at' AS c, 'under' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''He is good ___ mathematics.''' AS q, 'at' AS a, 'for' AS b, 'on' AS c, 'in' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''She has been married ___ him for five years.''' AS q, 'with' AS a, 'for' AS b, 'to' AS c, 'by' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''The cat hid ___ the cupboard.''' AS q, 'under' AS a, 'over' AS b, 'between' AS c, 'behind' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''It depends ___ the weather.''' AS q, 'in' AS a, 'on' AS b, 'of' AS c, 'for' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''She is afraid ___ dogs.''' AS q, 'with' AS a, 'of' AS b, 'about' AS c, 'for' AS d, 'B' AS k
    UNION ALL SELECT 'Add the correct tag: ''You are coming, ___?''' AS q, 'are you' AS a, 'aren''t you' AS b, 'do you' AS c, 'will you' AS d, 'B' AS k
    UNION ALL SELECT 'Add the correct tag: ''Let us go, ___?''' AS q, 'are we' AS a, 'shall we' AS b, 'will we' AS c, 'do we' AS d, 'B' AS k
    UNION ALL SELECT 'Add the correct tag: ''She is a nurse, ___?''' AS q, 'is she' AS a, 'does she' AS b, 'isn''t she' AS c, 'was she' AS d, 'C' AS k
    UNION ALL SELECT 'Add the correct tag: ''Nobody called you, ___?''' AS q, 'didn''t they' AS a, 'do they' AS b, 'aren''t they' AS c, 'did they' AS d, 'D' AS k
    UNION ALL SELECT 'Add the correct tag: ''Open the door, ___?''' AS q, 'you will' AS a, 'do you' AS b, 'will you' AS c, 'you are' AS d, 'C' AS k
    UNION ALL SELECT 'Change to passive voice: ''The teacher punished the boy.''' AS q, 'The teacher was punished by the boy.' AS a, 'The boy was punished by the teacher.' AS b, 'The teacher has punished the boy.' AS c, 'The boy is punished by the teacher.' AS d, 'B' AS k
    UNION ALL SELECT 'Change to passive voice: ''They built the bridge in 1990.''' AS q, 'The bridge is built in 1990.' AS a, 'The bridge has been built in 1990.' AS b, 'The bridge was built in 1990.' AS c, 'The bridge built in 1990.' AS d, 'C' AS k
    UNION ALL SELECT 'Change to passive voice: ''The farmer grows yams.''' AS q, 'Yams grew by the farmer.' AS a, 'Yams are grown by the farmer.' AS b, 'Yams were grown by the farmer.' AS c, 'The yams are growing by the farmer.' AS d, 'B' AS k
    UNION ALL SELECT 'Change to interrogative form: ''He lost his key.''' AS q, 'Did he lose his key?' AS a, 'Did he lost his key?' AS b, 'Has he lost his key?' AS c, 'He did lose his key?' AS d, 'A' AS k
    UNION ALL SELECT 'Change to interrogative form: ''We have never seen a lion.''' AS q, 'Did we ever see a lion?' AS a, 'Do we ever saw a lion?' AS b, 'Have we ever seen a lion?' AS c, 'We have ever seen a lion?' AS d, 'C' AS k
    UNION ALL SELECT 'Change to negative form: ''The girl is dancing.''' AS q, 'The girl do not dance.' AS a, 'The girl was not dance.' AS b, 'The girl is not dancing.' AS c, 'The girl not is dancing.' AS d, 'C' AS k
    UNION ALL SELECT 'Change to past tense: ''He is a pilot.''' AS q, 'He would be a pilot.' AS a, 'He will be a pilot.' AS b, 'He has been a pilot.' AS c, 'He was a pilot.' AS d, 'D' AS k
    UNION ALL SELECT 'The vowel sound in the word ''book'' is' AS q, '/e/' AS a, '/ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ/' AS b, '/ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ/' AS c, '/ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ/' AS d, 'D' AS k
    UNION ALL SELECT 'Which of the following is a voiceless consonant sound?' AS q, '/v/' AS a, '/b/' AS b, '/p/' AS c, '/d/' AS d, 'C' AS k
    UNION ALL SELECT 'The ''ch'' in the word ''chair'' is best described as a' AS q, 'digraph' AS a, 'diphthong' AS b, 'monophthong' AS c, 'schwa' AS d, 'A' AS k
    UNION ALL SELECT 'A syllable is best defined as' AS q, 'a unit of sound' AS a, 'a letter of the alphabet' AS b, 'a written word only' AS c, 'a pause in writing' AS d, 'A' AS k
    UNION ALL SELECT 'Two words written together but pronounced separately form a' AS q, 'diphthong' AS a, 'hiatus' AS b, 'elision' AS c, 'liaison' AS d, 'B' AS k
    UNION ALL SELECT 'In the word ''photograph'', the primary stress falls on the' AS q, 'third syllable' AS a, 'last syllable' AS b, 'first syllable' AS c, 'second syllable' AS d, 'C' AS k
    UNION ALL SELECT 'A fall in intonation at the end of a sentence usually signals' AS q, 'certainty or finality' AS a, 'a question' AS b, 'a warning' AS c, 'an unfinished thought' AS d, 'A' AS k
    UNION ALL SELECT 'Which of the following is a nasal consonant?' AS q, '/m/' AS a, '/f/' AS b, '/p/' AS c, '/k/' AS d, 'A' AS k
    UNION ALL SELECT 'Which of the following is a plosive consonant?' AS q, '/m/' AS a, '/s/' AS b, '/n/' AS c, '/t/' AS d, 'D' AS k
    UNION ALL SELECT 'Choose the word closest in meaning to ''big''' AS q, 'tiny' AS a, 'narrow' AS b, 'weak' AS c, 'large' AS d, 'D' AS k
    UNION ALL SELECT 'Choose the word opposite in meaning to ''kill''' AS q, 'destroy' AS a, 'spare' AS b, 'waste' AS c, 'end' AS d, 'B' AS k
    UNION ALL SELECT 'The expression ''a drop in the ocean'' means' AS q, 'a sudden flood' AS a, 'a noisy complaint' AS b, 'a very small amount' AS c, 'a very large amount' AS d, 'C' AS k
    UNION ALL SELECT 'The expression ''to err on the side of caution'' means to' AS q, 'act regardless of risk' AS a, 'act quickly without thought' AS b, 'make frequent mistakes' AS c, 'be careful and avoid risk' AS d, 'D' AS k
    UNION ALL SELECT 'Which of the following is a suitable greeting in a formal letter?' AS q, 'Good evening you' AS a, 'Hi there' AS b, 'Dear Sir or Madam' AS c, 'My friend' AS d, 'C' AS k
    UNION ALL SELECT 'The main purpose of writing a summary is to' AS q, 'reproduce every detail' AS a, 'express personal opinion' AS b, 'persuade the reader' AS c, 'give the main points in fewer words' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''He was tired, ___ he continued working.''' AS q, 'but' AS a, 'so' AS b, 'because' AS c, 'although' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''She studied very hard, ___ she passed the examination.''' AS q, 'or' AS a, 'so' AS b, 'but' AS c, 'nor' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the sentence: ''It was raining heavily; ___, the match was cancelled.''' AS q, 'however' AS a, 'nevertheless' AS b, 'otherwise' AS c, 'therefore' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''___ he was tired, he went to bed early.''' AS q, 'Although' AS a, 'However' AS b, 'Because' AS c, 'So' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''He will come to the party ___ he is invited.''' AS q, 'while' AS a, 'unless' AS b, 'if' AS c, 'though' AS d, 'C' AS k
    UNION ALL SELECT 'Which sentence is correctly punctuated?' AS q, 'The teacher asked,Where are you going?' AS a, 'The teacher asked me where I was going?' AS b, 'The teacher asked Where are you going' AS c, 'The teacher asked, where are you going' AS d, 'B' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'He has went home.' AS a, 'He have gone home.' AS b, 'He has gone home.' AS c, 'He had gone to home.' AS d, 'C' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'I do not have many time.' AS a, 'I do not have much time.' AS b, 'I do not have many times.' AS c, 'I do not has much time.' AS d, 'B' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'The furniture are new one.' AS a, 'The furniture is new.' AS b, 'The furnitures is new.' AS c, 'The furniture are new.' AS d, 'B' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'She is more taller than her sister.' AS a, 'She is more tall than her sister.' AS b, 'She is tallest than her sister.' AS c, 'She is taller than her sister.' AS d, 'D' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'Each of the students have books.' AS a, 'Each of the students have a book.' AS b, 'Each of the students has a book.' AS c, 'Each of the student have a book.' AS d, 'C' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'Me and my brother went to the market.' AS a, 'I and my brother went to the market.' AS b, 'My brother and me went to the market.' AS c, 'My brother and I went to the market.' AS d, 'D' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'I am knowing the answer.' AS a, 'I am known the answer.' AS b, 'I know the answer.' AS c, 'I have knowing the answer.' AS d, 'C' AS k
    UNION ALL SELECT 'Which sentence has no error?' AS q, 'One of my friends is a doctor.' AS a, 'One of my friend is a doctor.' AS b, 'One of my friends are a doctor.' AS c, 'One of my friend are doctors.' AS d, 'A' AS k
    UNION ALL SELECT 'The part of speech of ''beautiful'' in ''She wore a beautiful gown'' is' AS q, 'noun' AS a, 'conjunction' AS b, 'adverb' AS c, 'adjective' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''Hardly had I arrived ___ it began to rain.''' AS q, 'when' AS a, 'than' AS b, 'then' AS c, 'that' AS d, 'A' AS k
    UNION ALL SELECT 'Complete the sentence: ''She has been living here ___ 2019.''' AS q, 'by' AS a, 'since' AS b, 'for' AS c, 'from' AS d, 'B' AS k
    UNION ALL SELECT 'Choose the correct form: ''I would rather you ___ me now.''' AS q, 'help' AS a, 'would help' AS b, 'helped' AS c, 'helping' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the sentence: ''The evidence against him was ___; nobody believed him.''' AS q, 'conclusive' AS a, 'ambiguous' AS b, 'impartial' AS c, 'inconclusive' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''The principal, as well as his assistants, ___ present.''' AS q, 'are' AS a, 'was' AS b, 'were' AS c, 'is' AS d, 'D' AS k
    UNION ALL SELECT 'The tone conveyed by the expression ''Bless you'' is' AS q, 'grateful' AS a, 'angry' AS b, 'doubtful' AS c, 'sarcastic' AS d, 'A' AS k
    UNION ALL SELECT 'Which of the following is correctly spelt?' AS q, 'Accomodation' AS a, 'Accommodation' AS b, 'Acommodation' AS c, 'Acomodation' AS d, 'B' AS k
    UNION ALL SELECT 'Which of the following is correctly spelt?' AS q, 'Ocurrance' AS a, 'Occurence' AS b, 'Occurrence' AS c, 'Ocurrence' AS d, 'C' AS k
    UNION ALL SELECT 'Choose the correct homophone: ''I will ___ you tomorrow.''' AS q, 'write' AS a, 'rite' AS b, 'writ' AS c, 'right' AS d, 'D' AS k
    UNION ALL SELECT 'Choose the correct homophone: ''Put the books on the ___.''' AS q, 'self' AS a, 'shelf' AS b, 'shell' AS c, 'shelved' AS d, 'B' AS k
    UNION ALL SELECT 'Passage: A young girl named Amaka walked to the market every Saturday to help her mother sell vegetables. She arranged the produce and counted the money at the end of the day. What is Amaka''s main responsibility?' AS q, 'Buying food for the family' AS a, 'Helping her mother sell vegetables' AS b, 'Attending school during the week' AS c, 'Learning how to drive' AS d, 'B' AS k
    UNION ALL SELECT 'Passage: The examination was scheduled for Tuesday, but heavy rain fell on the morning of the exam. Nevertheless, many candidates arrived early and the papers started at ten o''clock. Why was the examination delayed?' AS q, 'The venue was too small' AS a, 'The invigilator was absent' AS b, 'It rained heavily' AS c, 'Candidates arrived too late' AS d, 'C' AS k
    UNION ALL SELECT 'Passage: Many people believe that reading improves concentration, vocabulary and general knowledge. However, the benefits are lost when one reads scattered materials without understanding. What is the writer''s advice?' AS q, 'Read with understanding' AS a, 'Read only newspapers' AS b, 'Read scattered materials' AS c, 'Stop reading altogether' AS d, 'A' AS k
    UNION ALL SELECT 'Which register is appropriate for a speech at a school assembly?' AS q, 'Formal' AS a, 'Idiomatic' AS b, 'Slang' AS c, 'Colloquial' AS d, 'A' AS k
    UNION ALL SELECT 'The phrase ''to keep one''s fingers crossed'' means to' AS q, 'be very careful' AS a, 'be very angry' AS b, 'work very hard' AS c, 'wish for good luck' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the sentence: ''The chairman, together with his directors, ___ arrived.''' AS q, 'have' AS a, 'are' AS b, 'has' AS c, 'were' AS d, 'C' AS k
    UNION ALL SELECT 'Which of the following is a subordinate conjunction?' AS q, 'although' AS a, 'and' AS b, 'but' AS c, 'or' AS d, 'A' AS k
    UNION ALL SELECT 'The noun in ''The crowd cheered loudly'' is' AS q, 'collective' AS a, 'proper' AS b, 'material' AS c, 'abstract' AS d, 'A' AS k
    UNION ALL SELECT 'Which sentence best avoids ambiguity?' AS q, 'He saw the man with the telescope.' AS a, 'Using a telescope, the man saw him.' AS b, 'It was the man with the telescope who saw him.' AS c, 'He used the telescope to look at the man.' AS d, 'B' AS k
    UNION ALL SELECT '''Not until he arrived did we know the truth.'' This shows' AS q, 'passive voice' AS a, 'normal word order' AS b, 'inversion after a negative adverbial' AS c, 'exclamatory emphasis' AS d, 'C' AS k
  ) t ON 1 = 1
 WHERE s.subject_code = 'ENG201'
   AND NOT EXISTS (SELECT 1 FROM questions x WHERE x.subject_id = s.id);

-- ------------------------------------------------------------
-- 8. Questions for MTH201 (118)
-- ------------------------------------------------------------

-- The NOT EXISTS guard means a subject that already has questions
-- is left untouched, so a re-run cannot duplicate the pool.
INSERT INTO questions
    (subject_id, question_text, option_a, option_b, option_c, option_d, correct_option)
SELECT s.id, t.q, t.a, t.b, t.c, t.d, t.k
  FROM subjects s
  JOIN (
    SELECT 'What is the place value of 7 in 4,782?' AS q, '700' AS a, '7,000' AS b, '70' AS c, '70,000' AS d, 'B' AS k
    UNION ALL SELECT 'What is the place value of 4 in 4,782?' AS q, '4,000' AS a, '40' AS b, '400' AS c, '4' AS d, 'C' AS k
    UNION ALL SELECT 'What is the place value of 8 in 4,782?' AS q, '80' AS a, '8' AS b, '80,000' AS c, '800' AS d, 'A' AS k
    UNION ALL SELECT 'Round 6,743 to the nearest hundred.' AS q, '6,740' AS a, '6,800' AS b, '6,750' AS c, '6,700' AS d, 'D' AS k
    UNION ALL SELECT 'Round 8,451 to the nearest hundred.' AS q, '8,400' AS a, '8,460' AS b, '8,450' AS c, '8,500' AS d, 'D' AS k
    UNION ALL SELECT 'Round 2,318 to the nearest ten.' AS q, '2,310' AS a, '2,300' AS b, '2,330' AS c, '2,320' AS d, 'D' AS k
    UNION ALL SELECT 'What is the value of 5 raised to the power of 3?' AS q, '125' AS a, '15' AS b, '25' AS c, '50' AS d, 'A' AS k
    UNION ALL SELECT 'What is the value of the square root of 144?' AS q, '14' AS a, '16' AS b, '12' AS c, '18' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these numbers is the largest?' AS q, '1,200' AS a, '1,024' AS b, '1,204' AS c, '1,240' AS d, 'D' AS k
    UNION ALL SELECT 'Arrange these in ascending order: 3, 7, 1, 5' AS q, '1, 5, 3, 7' AS a, '1, 3, 5, 7' AS b, '3, 7, 1, 5' AS c, '7, 5, 3, 1' AS d, 'B' AS k
    UNION ALL SELECT 'What is the greatest common divisor of 12 and 18?' AS q, '3' AS a, '6' AS b, '12' AS c, '9' AS d, 'B' AS k
    UNION ALL SELECT 'What is the lowest common multiple of 4 and 6?' AS q, '24' AS a, '10' AS b, '8' AS c, '12' AS d, 'D' AS k
    UNION ALL SELECT 'Simplify the fraction 4 over 8 to its lowest terms.' AS q, '1 over 2' AS a, '2 over 4' AS b, '1 over 4' AS c, '2 over 1' AS d, 'A' AS k
    UNION ALL SELECT 'Which fraction is the largest?' AS q, '1 over 3' AS a, '1 over 4' AS b, '1 over 5' AS c, '1 over 2' AS d, 'D' AS k
    UNION ALL SELECT 'Write 3/4 as a decimal number.' AS q, '0.75' AS a, '0.25' AS b, '0.43' AS c, '0.34' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is a proper fraction?' AS q, '7 over 4' AS a, '5 over 3' AS b, '9 over 2' AS c, '4 over 7' AS d, 'D' AS k
    UNION ALL SELECT 'If 2n + 5 = 17, what is the value of n?' AS q, '6' AS a, '11' AS b, '7' AS c, '5' AS d, 'A' AS k
    UNION ALL SELECT 'If 3x - 4 = 11, what is the value of x?' AS q, '5' AS a, '7' AS b, '6' AS c, '15' AS d, 'A' AS k
    UNION ALL SELECT 'Solve for y: y divided by 4 equals 9' AS q, '13' AS a, '5' AS b, '36' AS c, '40' AS d, 'C' AS k
    UNION ALL SELECT 'What is the value of n if n squared equals 81?' AS q, '9' AS a, '27' AS b, '18' AS c, '3' AS d, 'A' AS k
    UNION ALL SELECT 'What is the sum of the first five positive whole numbers?' AS q, '25' AS a, '15' AS b, '20' AS c, '10' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is an even number?' AS q, '48' AS a, '33' AS b, '27' AS c, '51' AS d, 'A' AS k
    UNION ALL SELECT 'The opposite of -8 is' AS q, '-8' AS a, '16' AS b, '8' AS c, '0' AS d, 'C' AS k
    UNION ALL SELECT 'What is the mean of 4, 8, 10 and 14?' AS q, '9' AS a, '10' AS b, '11' AS c, '8' AS d, 'A' AS k
    UNION ALL SELECT 'The median of 3, 5, 7, 9 and 11 is' AS q, '5' AS a, '9' AS b, '8' AS c, '7' AS d, 'D' AS k
    UNION ALL SELECT 'The mode of 2, 4, 4, 6 and 8 is' AS q, '2' AS a, '4' AS b, '6' AS c, '8' AS d, 'B' AS k
    UNION ALL SELECT 'What is the range of 3, 9, 4, 12 and 7?' AS q, '9' AS a, '15' AS b, '12' AS c, '7' AS d, 'A' AS k
    UNION ALL SELECT 'What is 15 percent of 200?' AS q, '150' AS a, '15' AS b, '30' AS c, '250' AS d, 'C' AS k
    UNION ALL SELECT 'A shop gives a 10 percent discount on a 5,000 naira item. What is the selling price?' AS q, '4,000' AS a, '4,500' AS b, '4,950' AS c, '5,000' AS d, 'B' AS k
    UNION ALL SELECT 'A student scored 45 out of 60 in a test. What is the percentage score?' AS q, '70' AS a, '80' AS b, '75' AS c, '85' AS d, 'C' AS k
    UNION ALL SELECT 'What is 2 to the power of 5?' AS q, '10' AS a, '32' AS b, '16' AS c, '25' AS d, 'B' AS k
    UNION ALL SELECT 'How many minutes are there in 2 and a half hours?' AS q, '120' AS a, '180' AS b, '200' AS c, '150' AS d, 'D' AS k
    UNION ALL SELECT 'How many seconds are there in 5 minutes?' AS q, '300' AS a, '600' AS b, '500' AS c, '350' AS d, 'A' AS k
    UNION ALL SELECT 'How many days are there in a leap year?' AS q, '366' AS a, '365' AS b, '364' AS c, '367' AS d, 'A' AS k
    UNION ALL SELECT 'What is the perimeter of a rectangle whose length is 8 cm and width is 5 cm?' AS q, '13 cm' AS a, '26 cm' AS b, '26 square cm' AS c, '40 cm' AS d, 'B' AS k
    UNION ALL SELECT 'What is the area of a rectangle of length 9 m and width 4 m?' AS q, '13 square m' AS a, '26 square m' AS b, '36 square m' AS c, '36 m' AS d, 'C' AS k
    UNION ALL SELECT 'What is the area of a square of side 6 cm?' AS q, '24 square cm' AS a, '36 square cm' AS b, '12 square cm' AS c, '30 square cm' AS d, 'B' AS k
    UNION ALL SELECT 'What is the volume of a cuboid of dimensions 2 cm, 3 cm and 5 cm?' AS q, '30 cubic cm' AS a, '10 cubic cm' AS b, '15 cubic cm' AS c, '60 cubic cm' AS d, 'A' AS k
    UNION ALL SELECT 'What is the value of pi to two decimal places?' AS q, '2.14' AS a, '31.4' AS b, '3.14' AS c, '3.41' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is the correct formula for the area of a triangle?' AS q, 'A equals base plus height' AS a, 'A equals base times height' AS b, 'A equals half of base squared' AS c, 'A equals half of base times height' AS d, 'D' AS k
    UNION ALL SELECT 'The angles of a triangle add up to' AS q, '90 degrees' AS a, '180 degrees' AS b, '360 degrees' AS c, '270 degrees' AS d, 'B' AS k
    UNION ALL SELECT 'How many degrees are there in a right angle?' AS q, '45' AS a, '90' AS b, '180' AS c, '360' AS d, 'B' AS k
    UNION ALL SELECT 'A line that divides a circle into two equal parts is called a' AS q, 'radius' AS a, 'diameter' AS b, 'chord' AS c, 'arc' AS d, 'B' AS k
    UNION ALL SELECT 'Two parallel lines cut by a transversal form how many pairs of co-interior angles?' AS q, 'One' AS a, 'Three' AS b, 'Two' AS c, 'Four' AS d, 'B' AS k
    UNION ALL SELECT 'What is the name of the angle that measures 90 degrees?' AS q, 'Reflex' AS a, 'Obtuse' AS b, 'Right' AS c, 'Acute' AS d, 'C' AS k
    UNION ALL SELECT 'Evaluate 15 + 8 times 3 - 2.' AS q, '43' AS a, '19' AS b, '45' AS c, '37' AS d, 'D' AS k
    UNION ALL SELECT 'Evaluate 36 divided by 6 plus 4.' AS q, '2' AS a, '12' AS b, '10' AS c, '6' AS d, 'C' AS k
    UNION ALL SELECT 'Evaluate 5 squared plus 3 times 2.' AS q, '21' AS a, '19' AS b, '31' AS c, '25' AS d, 'B' AS k
    UNION ALL SELECT 'Evaluate (2 + 3) times 4 minus 5.' AS q, '20' AS a, '23' AS b, '15' AS c, '25' AS d, 'C' AS k
    UNION ALL SELECT 'What is 10 percent of 350?' AS q, '25' AS a, '35' AS b, '350' AS c, '3500' AS d, 'B' AS k
    UNION ALL SELECT 'A farmer harvests 24 bags of maize and sells them at 1,500 naira each. How much is this worth?' AS q, '36,000' AS a, '30,000' AS b, '15,000' AS c, '24,000' AS d, 'A' AS k
    UNION ALL SELECT 'How many boxes of 24 bottles each can be filled from 600 bottles?' AS q, '24' AS a, '20' AS b, '25' AS c, '30' AS d, 'C' AS k
    UNION ALL SELECT 'What is the cost of 7 oranges at 45 naira each?' AS q, '280' AS a, '350' AS b, '315' AS c, '320' AS d, 'C' AS k
    UNION ALL SELECT 'A bus carries 50 passengers. How many passengers in 6 buses?' AS q, '350' AS a, '3000' AS b, '560' AS c, '300' AS d, 'D' AS k
    UNION ALL SELECT 'What is the smallest three-digit number?' AS q, '101' AS a, '110' AS b, '999' AS c, '100' AS d, 'D' AS k
    UNION ALL SELECT 'What is the largest two-digit prime number?' AS q, '99' AS a, '91' AS b, '97' AS c, '89' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a multiple of 9?' AS q, '49' AS a, '45' AS b, '47' AS c, '46' AS d, 'B' AS k
    UNION ALL SELECT 'What is the next number in the sequence 2, 4, 6, 8, ___?' AS q, '10' AS a, '11' AS b, '9' AS c, '12' AS d, 'A' AS k
    UNION ALL SELECT 'What is the next number in the sequence 3, 6, 12, 24, ___?' AS q, '30' AS a, '48' AS b, '60' AS c, '36' AS d, 'B' AS k
    UNION ALL SELECT 'Complete the pattern: 1, 3, 5, 7, ___' AS q, '8' AS a, '10' AS b, '9' AS c, '11' AS d, 'C' AS k
    UNION ALL SELECT 'Complete the pattern: 100, 90, 80, 70, ___' AS q, '60' AS a, '65' AS b, '69' AS c, '55' AS d, 'A' AS k
    UNION ALL SELECT 'Evaluate sin 30 degrees.' AS q, '0.5' AS a, '0.866' AS b, '1' AS c, 'root 3 over 2' AS d, 'A' AS k
    UNION ALL SELECT 'Evaluate cos 60 degrees.' AS q, 'root 3 over 2' AS a, '1' AS b, '0.866' AS c, '0.5' AS d, 'D' AS k
    UNION ALL SELECT 'Evaluate tan 45 degrees.' AS q, 'root 3' AS a, '0' AS b, '2' AS c, '1' AS d, 'D' AS k
    UNION ALL SELECT 'What is the hypotenuse of a right-angled triangle with legs 3 cm and 4 cm?' AS q, '6 cm' AS a, '5 cm' AS b, '12 cm' AS c, '7 cm' AS d, 'B' AS k
    UNION ALL SELECT 'What is the value of 3 to the power of 0?' AS q, '0' AS a, '3' AS b, '1' AS c, '9' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these expressions is a prime number?' AS q, '91' AS a, '87' AS b, '93' AS c, '89' AS d, 'D' AS k
    UNION ALL SELECT 'What is the cube root of 125?' AS q, '3' AS a, '15' AS b, '5' AS c, '25' AS d, 'C' AS k
    UNION ALL SELECT 'Convert 0.6 to a fraction in lowest terms.' AS q, '5 over 8' AS a, '3 over 4' AS b, '2 over 3' AS c, '3 over 5' AS d, 'D' AS k
    UNION ALL SELECT 'If a number is increased by 20% and the result is 240, what was the number?' AS q, '200' AS a, '220' AS b, '192' AS c, '180' AS d, 'A' AS k
    UNION ALL SELECT 'A quantity increases from 50 to 60. What is the percentage increase?' AS q, '10%' AS a, '20%' AS b, '25%' AS c, '16.67%' AS d, 'B' AS k
    UNION ALL SELECT 'The coordinates of point P are (3, 5). Which quadrant is it in?' AS q, 'Quadrant II' AS a, 'Quadrant III' AS b, 'Quadrant IV' AS c, 'Quadrant I' AS d, 'D' AS k
    UNION ALL SELECT 'How many axes of symmetry does a square have?' AS q, 'Four' AS a, 'One' AS b, 'Two' AS c, 'Three' AS d, 'A' AS k
    UNION ALL SELECT 'What is the sum of interior angles of a triangle?' AS q, '180 degrees' AS a, '90 degrees' AS b, '360 degrees' AS c, '270 degrees' AS d, 'A' AS k
    UNION ALL SELECT 'Evaluate 3 factorial.' AS q, '12' AS a, '6' AS b, '3' AS c, '9' AS d, 'B' AS k
    UNION ALL SELECT 'If the HCF of two numbers is 6 and one number is 24, which could be a common multiple of both?' AS q, '24' AS a, '12' AS b, '48' AS c, '30' AS d, 'C' AS k
    UNION ALL SELECT 'How many naira is 5 fifty naira notes?' AS q, '55' AS a, '250' AS b, '550' AS c, '500' AS d, 'B' AS k
    UNION ALL SELECT 'What is the value of 27 divided by 9?' AS q, '6' AS a, '3' AS b, '9' AS c, '18' AS d, 'B' AS k
    UNION ALL SELECT 'If 3 pencils cost 90 naira, how much will 7 pencils cost?' AS q, '180' AS a, '240' AS b, '270' AS c, '210' AS d, 'D' AS k
    UNION ALL SELECT 'What is the average of 10, 20, 30 and 40?' AS q, '20' AS a, '30' AS b, '25' AS c, '35' AS d, 'C' AS k
    UNION ALL SELECT 'Evaluate 2 raised to the power of 8.' AS q, '512' AS a, '64' AS b, '128' AS c, '256' AS d, 'D' AS k
    UNION ALL SELECT 'What is the smallest prime number greater than 50?' AS q, '59' AS a, '53' AS b, '51' AS c, '61' AS d, 'B' AS k
    UNION ALL SELECT 'A right angle is exactly' AS q, '45 degrees' AS a, '90 degrees' AS b, '180 degrees' AS c, '120 degrees' AS d, 'B' AS k
    UNION ALL SELECT 'What is the value of x if 5x equals 35?' AS q, '5' AS a, '6' AS b, '7' AS c, '8' AS d, 'C' AS k
    UNION ALL SELECT 'Convert 5 centimeters to millimeters.' AS q, '50 mm' AS a, '0.5 mm' AS b, '500 mm' AS c, '5000 mm' AS d, 'A' AS k
    UNION ALL SELECT 'Convert 2 kilometers to meters.' AS q, '20 m' AS a, '2,000 m' AS b, '200 m' AS c, '20,000 m' AS d, 'B' AS k
    UNION ALL SELECT 'What is the value of 100 minus 37?' AS q, '73' AS a, '67' AS b, '53' AS c, '63' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is the correct order from least to greatest?' AS q, '1/4, 1/2, 1/8' AS a, '1/2, 1/4, 1/8' AS b, '1/2, 1/8, 1/4' AS c, '1/8, 1/4, 1/2' AS d, 'D' AS k
    UNION ALL SELECT 'Evaluate the median of 4, 4, 6, 8 and 10.' AS q, '4' AS a, '10' AS b, '8' AS c, '6' AS d, 'D' AS k
    UNION ALL SELECT 'A man buys 20 oranges at 30 naira each and sells them at 35 naira each. What is his profit?' AS q, '100' AS a, '50' AS b, '150' AS c, '200' AS d, 'A' AS k
    UNION ALL SELECT 'What is the value of 8 squared minus 4 squared?' AS q, '60' AS a, '48' AS b, '64' AS c, '12' AS d, 'B' AS k
    UNION ALL SELECT 'How many faces does a cube have?' AS q, '4' AS a, '8' AS b, '6' AS c, '12' AS d, 'C' AS k
    UNION ALL SELECT 'How many edges does a cuboid have?' AS q, '10' AS a, '8' AS b, '6' AS c, '12' AS d, 'D' AS k
    UNION ALL SELECT 'What is the sum of all exterior angles of any polygon?' AS q, '180 degrees' AS a, '360 degrees' AS b, '90 degrees' AS c, '270 degrees' AS d, 'B' AS k
    UNION ALL SELECT 'If the probability of an event is 0, what does it mean?' AS q, 'The event is certain' AS a, 'The event is impossible' AS b, 'The event is random' AS c, 'The event is likely' AS d, 'B' AS k
    UNION ALL SELECT 'The probability of NOT obtaining a head when a fair coin is tossed is' AS q, '1/4' AS a, '0' AS b, '1' AS c, '1/2' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a fair coin?' AS q, 'A coin with one head and one tail' AS a, 'A coin with two heads' AS b, 'A coin with two tails' AS c, 'A three-headed coin' AS d, 'A' AS k
    UNION ALL SELECT 'A bag contains 3 red and 7 blue balls. If one ball is drawn at random, what is the probability that it is red?' AS q, '3/10' AS a, '3/7' AS b, '7/10' AS c, '1/3' AS d, 'A' AS k
    UNION ALL SELECT 'Two fair dice are thrown. What is the probability that the total score is 2?' AS q, '1/3' AS a, '1/12' AS b, '1/6' AS c, '1/36' AS d, 'D' AS k
    UNION ALL SELECT 'How many outcomes are possible when two fair dice are thrown together?' AS q, '24' AS a, '36' AS b, '12' AS c, '48' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a multiple of both 3 and 4?' AS q, '12' AS a, '7' AS b, '5' AS c, '10' AS d, 'A' AS k
    UNION ALL SELECT 'What is the value of the median in 2, 4, 4, 6, 8?' AS q, '4' AS a, '5' AS b, '6' AS c, '2' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is a factor of 100?' AS q, '35' AS a, '25' AS b, '45' AS c, '55' AS d, 'B' AS k
    UNION ALL SELECT 'What is 1/5 expressed as a percentage?' AS q, '5%' AS a, '50%' AS b, '20%' AS c, '80%' AS d, 'C' AS k
    UNION ALL SELECT 'A shopkeeper buys 40 oranges and 5 are spoiled. How many are left?' AS q, '35' AS a, '30' AS b, '45' AS c, '40' AS d, 'A' AS k
    UNION ALL SELECT 'Evaluate the mean of 6, 8, 10 and 12.' AS q, '9' AS a, '10' AS b, '8' AS c, '11' AS d, 'A' AS k
    UNION ALL SELECT 'What is the sum of the first 10 natural numbers?' AS q, '55' AS a, '45' AS b, '100' AS c, '50' AS d, 'A' AS k
    UNION ALL SELECT 'If x is 4 and y is 7, what is the value of 2x plus 3y?' AS q, '21' AS a, '27' AS b, '23' AS c, '29' AS d, 'D' AS k
    UNION ALL SELECT 'What is the value of 3 to the power of 4?' AS q, '12' AS a, '27' AS b, '81' AS c, '64' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these numbers is a perfect square?' AS q, '45' AS a, '50' AS b, '64' AS c, '75' AS d, 'C' AS k
    UNION ALL SELECT 'What is the value of 144 divided by 12?' AS q, '14' AS a, '11' AS b, '12' AS c, '10' AS d, 'C' AS k
    UNION ALL SELECT 'A rectangle has a length of 12 cm and a width of 5 cm. What is its area?' AS q, '34 square cm' AS a, '17 square cm' AS b, '60 square cm' AS c, '60 cm' AS d, 'C' AS k
    UNION ALL SELECT 'What is the value of one quarter of 96?' AS q, '12' AS a, '48' AS b, '24' AS c, '32' AS d, 'C' AS k
    UNION ALL SELECT 'How many minutes are there in 3 and a half hours?' AS q, '210' AS a, '180' AS b, '200' AS c, '240' AS d, 'A' AS k
    UNION ALL SELECT 'What is the next term: 1, 4, 9, 16, ___?' AS q, '20' AS a, '24' AS b, '36' AS c, '25' AS d, 'D' AS k
    UNION ALL SELECT 'Complete the ratio 3 is to 9 as 4 is to ___' AS q, '10' AS a, '16' AS b, '12' AS c, '20' AS d, 'C' AS k
    UNION ALL SELECT 'If the angles of a polygon add up to 1080 degrees, how many sides has it?' AS q, '8' AS a, '7' AS b, '5' AS c, '6' AS d, 'D' AS k
    UNION ALL SELECT 'What is the value of 1 over 4 plus 1 over 4?' AS q, '1 over 4' AS a, '1 over 8' AS b, '1 over 2' AS c, '2 over 4' AS d, 'C' AS k
  ) t ON 1 = 1
 WHERE s.subject_code = 'MTH201'
   AND NOT EXISTS (SELECT 1 FROM questions x WHERE x.subject_id = s.id);

-- ------------------------------------------------------------
-- 9. Questions for PHY201 (140)
-- ------------------------------------------------------------

-- The NOT EXISTS guard means a subject that already has questions
-- is left untouched, so a re-run cannot duplicate the pool.
INSERT INTO questions
    (subject_id, question_text, option_a, option_b, option_c, option_d, correct_option)
SELECT s.id, t.q, t.a, t.b, t.c, t.d, t.k
  FROM subjects s
  JOIN (
    SELECT 'What is the SI unit of force?' AS q, 'Joule' AS a, 'Watt' AS b, 'Newton' AS c, 'Pascal' AS d, 'C' AS k
    UNION ALL SELECT 'What is the SI unit of energy?' AS q, 'Watt' AS a, 'Pascal' AS b, 'Joule' AS c, 'Newton' AS d, 'C' AS k
    UNION ALL SELECT 'What is the SI unit of power?' AS q, 'Watt' AS a, 'Joule' AS b, 'Newton' AS c, 'Ampere' AS d, 'A' AS k
    UNION ALL SELECT 'What is the SI unit of pressure?' AS q, 'Joule' AS a, 'Newton' AS b, 'Watt' AS c, 'Pascal' AS d, 'D' AS k
    UNION ALL SELECT 'What is the SI unit of electric current?' AS q, 'Volt' AS a, 'Ohm' AS b, 'Watt' AS c, 'Ampere' AS d, 'D' AS k
    UNION ALL SELECT 'What is the SI unit of electric charge?' AS q, 'Tesla' AS a, 'Volt' AS b, 'Ohm' AS c, 'Coulomb' AS d, 'D' AS k
    UNION ALL SELECT 'What is the SI unit of electric potential difference?' AS q, 'Volt' AS a, 'Ohm' AS b, 'Coulomb' AS c, 'Watt' AS d, 'A' AS k
    UNION ALL SELECT 'What is the SI unit of mass?' AS q, 'Newton' AS a, 'Pound' AS b, 'Kilogram' AS c, 'Gram' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a vector quantity?' AS q, 'Speed' AS a, 'Distance' AS b, 'Mass' AS c, 'Displacement' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a scalar quantity?' AS q, 'Velocity' AS a, 'Displacement' AS b, 'Force' AS c, 'Acceleration' AS d, 'B' AS k
    UNION ALL SELECT 'What is the SI unit of displacement?' AS q, 'Metre per second' AS a, 'Metre' AS b, 'Second' AS c, 'Kilometre per hour' AS d, 'B' AS k
    UNION ALL SELECT 'What is the SI unit of velocity?' AS q, 'Kilogram per second' AS a, 'Metre' AS b, 'Second' AS c, 'Metre per second' AS d, 'D' AS k
    UNION ALL SELECT 'What is the SI unit of acceleration?' AS q, 'Metre per second squared' AS a, 'Metre per second' AS b, 'Second squared' AS c, 'Kilogram per metre' AS d, 'A' AS k
    UNION ALL SELECT 'Speed is measured in' AS q, 'seconds' AS a, 'metres per second squared' AS b, 'metres' AS c, 'metres per second' AS d, 'D' AS k
    UNION ALL SELECT 'Distance is a' AS q, 'scalar quantity' AS a, 'vector quantity' AS b, 'dimension' AS c, 'unit' AS d, 'A' AS k
    UNION ALL SELECT 'A body at rest remains at rest unless acted upon by an unbalanced' AS q, 'mass' AS a, 'weight' AS b, 'moment' AS c, 'force' AS d, 'D' AS k
    UNION ALL SELECT 'Newton''s first law of motion is also known as the law of' AS q, 'acceleration' AS a, 'inertia' AS b, 'action and reaction' AS c, 'gravitation' AS d, 'B' AS k
    UNION ALL SELECT 'Newton''s second law of motion relates force to' AS q, 'mass and acceleration' AS a, 'momentum only' AS b, 'action and reaction' AS c, 'inertia' AS d, 'A' AS k
    UNION ALL SELECT 'Newton''s third law of motion is the law of' AS q, 'inertia' AS a, 'acceleration' AS b, 'action and reaction' AS c, 'gravitation' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a unit of impulse?' AS q, 'Newton second' AS a, 'Joule' AS b, 'Watt' AS c, 'Newton' AS d, 'A' AS k
    UNION ALL SELECT 'Impulse is equal to' AS q, 'force multiplied by mass' AS a, 'force multiplied by time' AS b, 'mass multiplied by velocity' AS c, 'energy divided by time' AS d, 'B' AS k
    UNION ALL SELECT 'Momentum is the product of mass and' AS q, 'velocity' AS a, 'acceleration' AS b, 'force' AS c, 'time' AS d, 'A' AS k
    UNION ALL SELECT 'A force of 10 N acting on a mass of 5 kg produces an acceleration of' AS q, '15 metre per second squared' AS a, '50 metre per second squared' AS b, '2 metre per second squared' AS c, '0.5 metre per second squared' AS d, 'C' AS k
    UNION ALL SELECT 'Weight is the product of mass and' AS q, 'friction' AS a, 'velocity' AS b, 'acceleration due to gravity' AS c, 'force' AS d, 'C' AS k
    UNION ALL SELECT 'What is the approximate value of acceleration due to gravity near the surface of the earth?' AS q, '10.8 metre per second squared' AS a, '98 metre per second squared' AS b, '0.98 metre per second squared' AS c, '9.8 metre per second squared' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a contact force?' AS q, 'Magnetic force' AS a, 'Friction' AS b, 'Electrostatic force' AS c, 'Gravitational force' AS d, 'B' AS k
    UNION ALL SELECT 'Friction is a force that opposes' AS q, 'motion' AS a, 'weight' AS b, 'gravity' AS c, 'electricity' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is not a contact force?' AS q, 'Tension' AS a, 'Normal reaction' AS b, 'Gravitational force' AS c, 'Friction' AS d, 'C' AS k
    UNION ALL SELECT 'Work is done when a force moves a body through a' AS q, 'time' AS a, 'distance' AS b, 'mass' AS c, 'velocity' AS d, 'B' AS k
    UNION ALL SELECT 'What is the SI unit of work?' AS q, 'Pascal' AS a, 'Newton' AS b, 'Joule' AS c, 'Watt' AS d, 'C' AS k
    UNION ALL SELECT 'Work equals force multiplied by' AS q, 'time' AS a, 'distance in the direction of the force' AS b, 'mass' AS c, 'speed' AS d, 'B' AS k
    UNION ALL SELECT 'Power is the rate of doing work and is measured in' AS q, 'newton' AS a, 'pascal' AS b, 'joule' AS c, 'watt' AS d, 'D' AS k
    UNION ALL SELECT 'A machine has an efficiency of' AS q, '75%' AS a, '100%' AS b, '50%' AS c, '0%' AS d, 'A' AS k
    UNION ALL SELECT 'Efficiency of a machine can never be' AS q, 'greater than 100%' AS a, 'less than 100%' AS b, 'equal to zero' AS c, 'equal to 100%' AS d, 'A' AS k
    UNION ALL SELECT 'How much work is done when a force of 20 N moves an object 5 m in the direction of the force?' AS q, '4 J' AS a, '100 J' AS b, '25 J' AS c, '400 J' AS d, 'B' AS k
    UNION ALL SELECT 'A lamp of 60 W is used for 5 hours. How much energy is used?' AS q, '1800 J' AS a, '300 J' AS b, '300 Wh' AS c, '3000 J' AS d, 'C' AS k
    UNION ALL SELECT 'Potential energy is energy stored due to' AS q, 'motion' AS a, 'height or position' AS b, 'heat' AS c, 'electricity' AS d, 'B' AS k
    UNION ALL SELECT 'Kinetic energy is the energy of' AS q, 'a moving body' AS a, 'a charged body' AS b, 'a hot body' AS c, 'a body at rest' AS d, 'A' AS k
    UNION ALL SELECT 'As a body falls, its gravitational potential energy is converted into' AS q, 'sound' AS a, 'electrical energy' AS b, 'kinetic energy' AS c, 'nuclear energy' AS d, 'C' AS k
    UNION ALL SELECT 'Energy can neither be created nor destroyed but can only be' AS q, 'destroyed' AS a, 'stored forever' AS b, 'lost' AS c, 'transformed from one form to another' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a renewable source of energy?' AS q, 'Coal' AS a, 'Petrol' AS b, 'Solar energy' AS c, 'Natural gas' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a non-renewable source of energy?' AS q, 'Water power' AS a, 'Coal' AS b, 'Wind' AS c, 'Solar energy' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these does not produce carbon dioxide when burned?' AS q, 'Coal' AS a, 'Hydrogen gas' AS b, 'Petrol' AS c, 'Natural gas' AS d, 'B' AS k
    UNION ALL SELECT 'What is the main gas in the atmosphere?' AS q, 'Carbon dioxide' AS a, 'Nitrogen' AS b, 'Hydrogen' AS c, 'Oxygen' AS d, 'B' AS k
    UNION ALL SELECT 'What is the gas plants absorb from the atmosphere during photosynthesis?' AS q, 'Oxygen' AS a, 'Nitrogen' AS b, 'Carbon dioxide' AS c, 'Hydrogen' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a greenhouse gas?' AS q, 'Oxygen' AS a, 'Nitrogen' AS b, 'Argon' AS c, 'Carbon dioxide' AS d, 'D' AS k
    UNION ALL SELECT 'Global warming is mainly caused by' AS q, 'the depletion of the ozone layer' AS a, 'reflection of sunlight from cities' AS b, 'the rise in sea level' AS c, 'excess carbon dioxide in the atmosphere' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a noise pollutant?' AS q, 'Heat' AS a, 'Loud sound' AS b, 'Smoke' AS c, 'Dust' AS d, 'B' AS k
    UNION ALL SELECT 'Water pollution can be reduced by' AS q, 'burning refuse near rivers' AS a, 'pouring chemicals into rivers' AS b, 'disposing waste properly in designated sites' AS c, 'cutting trees' AS d, 'C' AS k
    UNION ALL SELECT 'The ozone layer protects the earth from' AS q, 'radio waves' AS a, 'ultraviolet radiation' AS b, 'microwaves' AS c, 'infrared radiation' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a physical change?' AS q, 'Burning paper' AS a, 'Melting ice' AS b, 'Rusting iron' AS c, 'Burning wood' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a chemical change?' AS q, 'Melting wax' AS a, 'Dissolving salt' AS b, 'Rusting of iron' AS c, 'Breaking glass' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these substances is a conductor of electricity?' AS q, 'Rubber' AS a, 'Wood' AS b, 'Copper' AS c, 'Plastic' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these substances is an insulator?' AS q, 'Aluminium' AS a, 'Copper' AS b, 'Iron' AS c, 'Rubber' AS d, 'D' AS k
    UNION ALL SELECT 'The ability of a material to conduct heat is called' AS q, 'electrical resistance' AS a, 'magnetism' AS b, 'density' AS c, 'thermal conductivity' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these metals is the best conductor of electricity?' AS q, 'Aluminium' AS a, 'Zinc' AS b, 'Copper' AS c, 'Iron' AS d, 'C' AS k
    UNION ALL SELECT 'What is the common metal used for electric cables?' AS q, 'Rubber' AS a, 'Copper' AS b, 'Glass' AS c, 'Plastic' AS d, 'B' AS k
    UNION ALL SELECT 'Electric current flows from' AS q, 'high potential to low potential' AS a, 'low potential to high potential' AS b, 'positive to negative only' AS c, 'negative to positive only' AS d, 'A' AS k
    UNION ALL SELECT 'Electric current is measured using an instrument called' AS q, 'voltmeter' AS a, 'ammeter' AS b, 'galvanometer' AS c, 'resistor' AS d, 'B' AS k
    UNION ALL SELECT 'Electric potential difference is measured with a' AS q, 'tangent galvanometer' AS a, 'ammeter' AS b, 'voltmeter' AS c, 'ohmmeter' AS d, 'C' AS k
    UNION ALL SELECT 'Resistance is measured using a' AS q, 'ohmmeter' AS a, 'voltmeter' AS b, 'ammeter' AS c, 'wattmeter' AS d, 'A' AS k
    UNION ALL SELECT 'The instrument used to detect very small electric currents is a' AS q, 'galvanometer' AS a, 'ammeter' AS b, 'electroscope' AS c, 'voltmeter' AS d, 'A' AS k
    UNION ALL SELECT 'What is the SI unit of electrical resistance?' AS q, 'Volt' AS a, 'Ampere' AS b, 'Ohm' AS c, 'Watt' AS d, 'C' AS k
    UNION ALL SELECT 'What is the unit of electrical power?' AS q, 'Joule' AS a, 'Ohm' AS b, 'Ampere' AS c, 'Watt' AS d, 'D' AS k
    UNION ALL SELECT 'The opposition offered to the flow of current is called' AS q, 'charge' AS a, 'resistance' AS b, 'potential' AS c, 'capacity' AS d, 'B' AS k
    UNION ALL SELECT 'What is the unit of electric charge?' AS q, 'Ampere' AS a, 'Ohm' AS b, 'Volt' AS c, 'Coulomb' AS d, 'D' AS k
    UNION ALL SELECT 'An electric circuit must contain a' AS q, 'switch only' AS a, 'wire only' AS b, 'battery and switch' AS c, 'source of energy' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a complete circuit?' AS q, 'Two wires joined at one end' AS a, 'An insulator' AS b, 'A wire connected to a cell through a switch' AS c, 'A wire with a gap' AS d, 'C' AS k
    UNION ALL SELECT 'What is the effect of an electric current passing through a conductor?' AS q, 'It becomes heavier' AS a, 'It dissolves' AS b, 'It becomes a gas' AS c, 'It produces a magnetic field' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a magnetic material?' AS q, 'Iron' AS a, 'Copper' AS b, 'Wood' AS c, 'Glass' AS d, 'A' AS k
    UNION ALL SELECT 'A compass needle points in the direction of' AS q, 'the electric field' AS a, 'the magnetic north' AS b, 'gravity' AS c, 'wind' AS d, 'B' AS k
    UNION ALL SELECT 'The region around a magnet in which it can attract iron is called its' AS q, 'flux' AS a, 'poles' AS b, 'axis' AS c, 'magnetic field' AS d, 'D' AS k
    UNION ALL SELECT 'Like poles of a magnet' AS q, 'repel' AS a, 'attract' AS b, 'touch' AS c, 'have no force' AS d, 'A' AS k
    UNION ALL SELECT 'The two poles of a magnet are called the' AS q, 'north and south poles' AS a, 'anode and cathode' AS b, 'left and right' AS c, 'positive and negative' AS d, 'A' AS k
    UNION ALL SELECT 'What happens to the magnetic force when the distance between two poles is increased?' AS q, 'It increases' AS a, 'It decreases' AS b, 'It stays the same' AS c, 'It becomes zero' AS d, 'B' AS k
    UNION ALL SELECT 'Sound is a form of energy that travels as a' AS q, 'transverse wave' AS a, 'longitudinal wave' AS b, 'circular wave' AS c, 'heat wave' AS d, 'B' AS k
    UNION ALL SELECT 'Sound cannot travel through a' AS q, 'solid' AS a, 'vacuum' AS b, 'liquid' AS c, 'gas' AS d, 'B' AS k
    UNION ALL SELECT 'What is the SI unit of frequency?' AS q, 'Watt' AS a, 'Hertz' AS b, 'Decibel' AS c, 'Joule' AS d, 'B' AS k
    UNION ALL SELECT 'The loudness of a sound is measured using a' AS q, 'thermometer' AS a, 'voltmeter' AS b, 'speedometer' AS c, 'decibel meter' AS d, 'D' AS k
    UNION ALL SELECT 'The pitch of a sound depends on the' AS q, 'temperature' AS a, 'loudness' AS b, 'frequency' AS c, 'amplitude' AS d, 'C' AS k
    UNION ALL SELECT 'The loudness of a sound depends on its' AS q, 'frequency' AS a, 'speed' AS b, 'amplitude' AS c, 'pitch' AS d, 'C' AS k
    UNION ALL SELECT 'What is the speed of sound in air at room temperature?' AS q, 'About 3.3 metres per second' AS a, 'About 340 metres per second' AS b, 'About 34 metres per second' AS c, 'About 1,500 metres per second' AS d, 'B' AS k
    UNION ALL SELECT 'The bouncing of sound waves from a hard surface is called' AS q, 'refraction' AS a, 'echo' AS b, 'absorption' AS c, 'diffraction' AS d, 'B' AS k
    UNION ALL SELECT 'The minimum distance required for an echo to be heard is' AS q, '100 m' AS a, '1 m' AS b, '5 m' AS c, '17 m' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these changes the pitch of a sound?' AS q, 'Increasing the frequency' AS a, 'Decreasing the amplitude' AS b, 'Reducing the loudness' AS c, 'Increasing the volume' AS d, 'A' AS k
    UNION ALL SELECT 'A musical note that is an octave higher has' AS q, 'half the frequency' AS a, 'twice the frequency' AS b, 'the same amplitude' AS c, 'the same frequency' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a method of producing sound from vibration?' AS q, 'Burning wood' AS a, 'Melting ice' AS b, 'Charging a battery' AS c, 'Plucking a stretched string' AS d, 'D' AS k
    UNION ALL SELECT 'Light energy travels as a' AS q, 'longitudinal wave' AS a, 'sound wave' AS b, 'matter wave' AS c, 'transverse wave' AS d, 'D' AS k
    UNION ALL SELECT 'Light travels in a vacuum at a speed of' AS q, '3 x 10 to the power of 5 metres per second' AS a, '3 x 10 to the power of 6 metres per second' AS b, '3 x 10 to the power of 10 metres per second' AS c, '3 x 10 to the power of 8 metres per second' AS d, 'D' AS k
    UNION ALL SELECT 'The bouncing of light off a surface is called' AS q, 'reflection' AS a, 'diffraction' AS b, 'refraction' AS c, 'dispersion' AS d, 'A' AS k
    UNION ALL SELECT 'The splitting of white light into its component colours is called' AS q, 'reflection' AS a, 'dispersion' AS b, 'refraction' AS c, 'diffraction' AS d, 'B' AS k
    UNION ALL SELECT 'The bending of light as it passes from air into glass is called' AS q, 'diffraction' AS a, 'interference' AS b, 'refraction' AS c, 'reflection' AS d, 'C' AS k
    UNION ALL SELECT 'The angle of incidence is equal to the' AS q, 'angle of refraction' AS a, 'critical angle' AS b, 'angle of deviation' AS c, 'angle of reflection' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these travels fastest in air?' AS q, 'Sound' AS a, 'Light' AS b, 'A fast aeroplane' AS c, 'A falling stone' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a source of light?' AS q, 'A mirror' AS a, 'The sun' AS b, 'A lens' AS c, 'A glass sheet' AS d, 'B' AS k
    UNION ALL SELECT 'An object that produces its own light is said to be' AS q, 'reflective' AS a, 'non-luminous' AS b, 'transparent' AS c, 'luminous' AS d, 'D' AS k
    UNION ALL SELECT 'An object that does not produce its own light is said to be' AS q, 'non-luminous' AS a, 'luminous' AS b, 'shiny' AS c, 'bright' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is transparent?' AS q, 'A glass sheet' AS a, 'A metal sheet' AS b, 'A cardboard box' AS c, 'A wooden board' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is opaque?' AS q, 'A glass sheet' AS a, 'Clean water' AS b, 'A plastic film' AS c, 'A wooden board' AS d, 'D' AS k
    UNION ALL SELECT 'A convex lens is thicker in the middle than at the' AS q, 'edges only' AS a, 'edges' AS b, 'centre only' AS c, 'corners' AS d, 'B' AS k
    UNION ALL SELECT 'A concave lens is thinner in the middle than at the' AS q, 'edges only' AS a, 'edges' AS b, 'corners' AS c, 'sides' AS d, 'A' AS k
    UNION ALL SELECT 'A convex lens is also called a' AS q, 'converging lens' AS a, 'cylindrical lens' AS b, 'diverging lens' AS c, 'plane lens' AS d, 'A' AS k
    UNION ALL SELECT 'A concave lens is also called a' AS q, 'converging lens' AS a, 'diverging lens' AS b, 'convex lens' AS c, 'plane lens' AS d, 'B' AS k
    UNION ALL SELECT 'The power of a lens is measured in' AS q, 'dioptres' AS a, 'lumens' AS b, 'candelas' AS c, 'watts' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these forms a real image on a screen?' AS q, 'A convex lens' AS a, 'A concave lens' AS b, 'A plane mirror' AS c, 'A diverging lens' AS d, 'A' AS k
    UNION ALL SELECT 'A plane mirror always produces a' AS q, 'virtual and upright image' AS a, 'real and enlarged image' AS b, 'real and inverted image' AS c, 'virtual and diminished image' AS d, 'A' AS k
    UNION ALL SELECT 'The image in a plane mirror is' AS q, 'the same size as the object' AS a, 'smaller than the object' AS b, 'larger than the object' AS c, 'inverted' AS d, 'A' AS k
    UNION ALL SELECT 'The number of images formed by two plane mirrors at an angle of 90 degrees is' AS q, '4' AS a, '1' AS b, '2' AS c, '3' AS d, 'D' AS k
    UNION ALL SELECT 'A periscope makes use of two plane mirrors placed at' AS q, '60 degrees to each other' AS a, '45 degrees to each other' AS b, '90 degrees to each other' AS c, 'parallel to each other' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a defect of vision caused by a lens that is too weak?' AS q, 'Long sight' AS a, 'Astigmatism' AS b, 'Presbyopia' AS c, 'Short sight' AS d, 'A' AS k
    UNION ALL SELECT 'Short-sightedness is corrected using a' AS q, 'concave lens' AS a, 'bifocal lens' AS b, 'convex lens' AS c, 'cylindrical lens only' AS d, 'C' AS k
    UNION ALL SELECT 'Long-sightedness is corrected using a' AS q, 'convex lens' AS a, 'concave lens' AS b, 'plane lens' AS c, 'tinted lens' AS d, 'B' AS k
    UNION ALL SELECT 'The amount of light entering the eye is controlled by the' AS q, 'cornea' AS a, 'retina' AS b, 'iris' AS c, 'optic nerve' AS d, 'C' AS k
    UNION ALL SELECT 'The image is formed on the' AS q, 'retina' AS a, 'pupil' AS b, 'iris' AS c, 'cornea' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is the part of the eye that contains the light-sensitive cells?' AS q, 'Iris' AS a, 'Cornea' AS b, 'Pupil' AS c, 'Retina' AS d, 'D' AS k
    UNION ALL SELECT 'The white of the eye is called the' AS q, 'cornea' AS a, 'iris' AS b, 'sclera' AS c, 'retina' AS d, 'C' AS k
    UNION ALL SELECT 'The part of the eye that controls the colour of the eye is the' AS q, 'cornea' AS a, 'retina' AS b, 'optic nerve' AS c, 'iris' AS d, 'D' AS k
    UNION ALL SELECT 'The nerve along which light signals reach the brain is the' AS q, 'auditory nerve' AS a, 'motor nerve' AS b, 'optic nerve' AS c, 'sensory nerve' AS d, 'C' AS k
    UNION ALL SELECT 'Electric current is conventionally measured in' AS q, 'volts' AS a, 'ohms' AS b, 'watts' AS c, 'amperes' AS d, 'D' AS k
    UNION ALL SELECT 'A device that converts electrical energy to mechanical energy is a' AS q, 'capacitor' AS a, 'battery' AS b, 'resistor' AS c, 'motor' AS d, 'D' AS k
    UNION ALL SELECT 'A device that converts electrical energy to light and heat is a' AS q, 'resistor' AS a, 'capacitor' AS b, 'bulb' AS c, 'switch' AS d, 'C' AS k
    UNION ALL SELECT 'A device that stores electrical energy is a' AS q, 'capacitor' AS a, 'switch' AS b, 'resistor' AS c, 'bulb' AS d, 'A' AS k
    UNION ALL SELECT 'The components that allow or prevent the flow of current are' AS q, 'bulbs' AS a, 'switches' AS b, 'capacitors' AS c, 'motors' AS d, 'B' AS k
    UNION ALL SELECT 'A circuit that can be switched on and off is fitted with a' AS q, 'battery' AS a, 'switch' AS b, 'bulb' AS c, 'resistor' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these conductors is used in the filament of a bulb?' AS q, 'Tungsten' AS a, 'Copper' AS b, 'Iron' AS c, 'Aluminium' AS d, 'A' AS k
    UNION ALL SELECT 'An electric heater converts electrical energy mainly into' AS q, 'chemical energy' AS a, 'sound energy' AS b, 'mechanical energy' AS c, 'light and heat energy' AS d, 'D' AS k
    UNION ALL SELECT 'What is the main physical property of a good conductor of heat?' AS q, 'High thermal conductivity' AS a, 'Low density' AS b, 'High electrical resistance' AS c, 'Low melting point' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is the best conductor of heat?' AS q, 'Wood' AS a, 'Rubber' AS b, 'Copper' AS c, 'Cork' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a poor conductor of heat?' AS q, 'Rubber' AS a, 'Copper' AS b, 'Aluminium' AS c, 'Iron' AS d, 'A' AS k
    UNION ALL SELECT 'A vacuum flask reduces heat loss by reducing' AS q, 'mass' AS a, 'volume' AS b, 'heat conduction and convection' AS c, 'pressure' AS d, 'C' AS k
    UNION ALL SELECT 'What is the rate of flow of heat measured in' AS q, 'joules per degree' AS a, 'joules per second' AS b, 'joules per kilogram' AS c, 'watts per square metre' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a method of measuring temperature?' AS q, 'Voltmeter' AS a, 'Barometer' AS b, 'Thermometer' AS c, 'Hygrometer' AS d, 'C' AS k
    UNION ALL SELECT 'A thermometric liquid that expands with temperature is' AS q, 'alcohol' AS a, 'water' AS b, 'brine' AS c, 'mercury' AS d, 'D' AS k
    UNION ALL SELECT 'A fixed point of the Celsius scale is' AS q, 'the average human body temperature' AS a, 'the temperature of a healthy room' AS b, 'the temperature of ice under standard pressure' AS c, 'the temperature of boiling water' AS d, 'C' AS k
    UNION ALL SELECT 'The temperature of pure melting ice under standard atmospheric pressure is' AS q, '37 degrees celsius' AS a, '100 degrees celsius' AS b, '32 degrees celsius' AS c, '0 degrees celsius' AS d, 'D' AS k
    UNION ALL SELECT 'The boiling point of water at standard atmospheric pressure is' AS q, '0 degrees celsius' AS a, '50 degrees celsius' AS b, '100 degrees celsius' AS c, '120 degrees celsius' AS d, 'C' AS k
    UNION ALL SELECT 'Absolute zero corresponds to' AS q, '-273 degrees celsius' AS a, '0 degrees celsius' AS b, '100 degrees celsius' AS c, '37 degrees celsius' AS d, 'A' AS k
    UNION ALL SELECT 'Heat transfer by circulation of a liquid is called' AS q, 'convection' AS a, 'insulation' AS b, 'conduction' AS c, 'radiation' AS d, 'A' AS k
    UNION ALL SELECT 'Heat transfer without a medium is called' AS q, 'conduction' AS a, 'convection' AS b, 'radiation' AS c, 'diffusion' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is the best conductor of heat used in cooking pots?' AS q, 'Wood' AS a, 'Paper' AS b, 'Aluminium' AS c, 'Plastic' AS d, 'C' AS k
  ) t ON 1 = 1
 WHERE s.subject_code = 'PHY201'
   AND NOT EXISTS (SELECT 1 FROM questions x WHERE x.subject_id = s.id);

-- ------------------------------------------------------------
-- 10. Questions for CHM201 (135)
-- ------------------------------------------------------------

-- The NOT EXISTS guard means a subject that already has questions
-- is left untouched, so a re-run cannot duplicate the pool.
INSERT INTO questions
    (subject_id, question_text, option_a, option_b, option_c, option_d, correct_option)
SELECT s.id, t.q, t.a, t.b, t.c, t.d, t.k
  FROM subjects s
  JOIN (
    SELECT 'What is the chemical symbol for gold?' AS q, 'Ag' AS a, 'Gd' AS b, 'Au' AS c, 'Go' AS d, 'C' AS k
    UNION ALL SELECT 'What is the chemical symbol for silver?' AS q, 'Si' AS a, 'Sv' AS b, 'Ag' AS c, 'Au' AS d, 'C' AS k
    UNION ALL SELECT 'What is the chemical symbol for iron?' AS q, 'Fe' AS a, 'Ir' AS b, 'In' AS c, 'I' AS d, 'A' AS k
    UNION ALL SELECT 'What is the chemical symbol for sodium?' AS q, 'No' AS a, 'Sd' AS b, 'Sm' AS c, 'Na' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for potassium?' AS q, 'Po' AS a, 'Pt' AS b, 'P' AS c, 'K' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for calcium?' AS q, 'Cm' AS a, 'Cl' AS b, 'C' AS c, 'Ca' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for oxygen?' AS q, 'O' AS a, 'Ox' AS b, 'Oxy' AS c, 'Om' AS d, 'A' AS k
    UNION ALL SELECT 'What is the chemical symbol for hydrogen?' AS q, 'Hg' AS a, 'He' AS b, 'H' AS c, 'Hy' AS d, 'C' AS k
    UNION ALL SELECT 'What is the chemical symbol for carbon?' AS q, 'Ca' AS a, 'Cb' AS b, 'Cr' AS c, 'C' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for nitrogen?' AS q, 'Ni' AS a, 'N' AS b, 'Nt' AS c, 'Ny' AS d, 'B' AS k
    UNION ALL SELECT 'What is the chemical symbol for copper?' AS q, 'Cp' AS a, 'Cu' AS b, 'Cr' AS c, 'Co' AS d, 'B' AS k
    UNION ALL SELECT 'What is the chemical symbol for lead?' AS q, 'L' AS a, 'Ld' AS b, 'Pd' AS c, 'Pb' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for chlorine?' AS q, 'Cl' AS a, 'Ch' AS b, 'C' AS c, 'Cn' AS d, 'A' AS k
    UNION ALL SELECT 'What is the chemical symbol for helium?' AS q, 'Hm' AS a, 'H' AS b, 'Hl' AS c, 'He' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for calcium oxide?' AS q, 'CaO' AS a, 'CaC' AS b, 'CaO2' AS c, 'Ca' AS d, 'A' AS k
    UNION ALL SELECT 'What is the chemical symbol for sodium chloride?' AS q, 'SmCl' AS a, 'NaC' AS b, 'NaCl2' AS c, 'NaCl' AS d, 'D' AS k
    UNION ALL SELECT 'What is the chemical symbol for water?' AS q, 'HO' AS a, 'H2O' AS b, 'OH' AS c, 'H2O2' AS d, 'B' AS k
    UNION ALL SELECT 'What is the chemical symbol for carbon dioxide?' AS q, 'CO2' AS a, 'CaO' AS b, 'CO' AS c, 'C2O' AS d, 'A' AS k
    UNION ALL SELECT 'What is the chemical symbol for hydrogen peroxide?' AS q, 'HO2' AS a, 'H2O' AS b, 'H2O2' AS c, 'O2H' AS d, 'C' AS k
    UNION ALL SELECT 'What is the chemical symbol for sulphuric acid?' AS q, 'H2SO4' AS a, 'HSO4' AS b, 'H2S' AS c, 'H2SO3' AS d, 'A' AS k
    UNION ALL SELECT 'How many elements are present in one molecule of water?' AS q, 'One' AS a, 'Two' AS b, 'Three' AS c, 'Four' AS d, 'B' AS k
    UNION ALL SELECT 'What is the atomic number of carbon?' AS q, '6' AS a, '8' AS b, '12' AS c, '14' AS d, 'A' AS k
    UNION ALL SELECT 'What is the atomic number of hydrogen?' AS q, '2' AS a, '6' AS b, '1' AS c, '8' AS d, 'C' AS k
    UNION ALL SELECT 'What is the atomic number of oxygen?' AS q, '9' AS a, '6' AS b, '8' AS c, '7' AS d, 'C' AS k
    UNION ALL SELECT 'What is the atomic number of nitrogen?' AS q, '6' AS a, '8' AS b, '14' AS c, '7' AS d, 'D' AS k
    UNION ALL SELECT 'What is the relative atomic mass of carbon?' AS q, '6' AS a, '12' AS b, '24' AS c, '14' AS d, 'B' AS k
    UNION ALL SELECT 'What is the relative atomic mass of oxygen?' AS q, '16' AS a, '8' AS b, '12' AS c, '32' AS d, 'A' AS k
    UNION ALL SELECT 'The number of protons in the nucleus of an atom is called the' AS q, 'mass number' AS a, 'neutron number' AS b, 'atomic number' AS c, 'valence' AS d, 'C' AS k
    UNION ALL SELECT 'The total number of protons and neutrons in the nucleus is called the' AS q, 'atomic number' AS a, 'mass number' AS b, 'neutron count' AS c, 'electron count' AS d, 'B' AS k
    UNION ALL SELECT 'The particles found in the nucleus of an atom are' AS q, 'electrons and photons' AS a, 'protons and electrons' AS b, 'protons and neutrons' AS c, 'neutrons and electrons' AS d, 'C' AS k
    UNION ALL SELECT 'The particles found around the nucleus of an atom are' AS q, 'protons' AS a, 'electrons' AS b, 'neutrons' AS c, 'ions' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is the maximum number of electrons in the first shell?' AS q, '8' AS a, '18' AS b, '6' AS c, '2' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is the maximum number of electrons in the second shell?' AS q, '8' AS a, '2' AS b, '6' AS c, '18' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is the maximum number of electrons in the third shell?' AS q, '18' AS a, '2' AS b, '6' AS c, '8' AS d, 'A' AS k
    UNION ALL SELECT 'The number of electrons in an atom is equal to the number of its' AS q, 'neutrons' AS a, 'protons' AS b, 'protons and neutrons' AS c, 'nuclei' AS d, 'B' AS k
    UNION ALL SELECT 'An atom becomes a cation when it' AS q, 'loses neutrons' AS a, 'gains electrons' AS b, 'loses electrons' AS c, 'gains protons' AS d, 'C' AS k
    UNION ALL SELECT 'An atom becomes an anion when it' AS q, 'loses electrons' AS a, 'gains electrons' AS b, 'loses protons' AS c, 'gains neutrons' AS d, 'B' AS k
    UNION ALL SELECT 'The loss of electrons from an atom is called' AS q, 'oxidation' AS a, 'displacement' AS b, 'combustion' AS c, 'reduction' AS d, 'A' AS k
    UNION ALL SELECT 'The gain of electrons by an atom is called' AS q, 'oxidation' AS a, 'condensation' AS b, 'reduction' AS c, 'neutralisation' AS d, 'C' AS k
    UNION ALL SELECT 'A substance made up of two or more elements chemically combined is called a' AS q, 'mixture' AS a, 'element' AS b, 'mixture of gases' AS c, 'compound' AS d, 'D' AS k
    UNION ALL SELECT 'A substance that cannot be broken down into simpler substances is called a' AS q, 'compound' AS a, 'mixture' AS b, 'element' AS c, 'solution' AS d, 'C' AS k
    UNION ALL SELECT 'A physical mixture of substances is different from a compound because a mixture' AS q, 'cannot be separated' AS a, 'can be separated by physical means' AS b, 'is always a gas' AS c, 'is always a solid' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a physical change?' AS q, 'Burning magnesium' AS a, 'Melting wax' AS b, 'Rusting iron' AS c, 'Adding acid to a metal carbonate' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a chemical change?' AS q, 'Dissolving sugar in water' AS a, 'Rusting iron' AS b, 'Breaking glass' AS c, 'Melting ice' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a reversible physical change?' AS q, 'Burning paper' AS a, 'Rusting iron' AS b, 'Freezing water' AS c, 'Burning magnesium' AS d, 'C' AS k
    UNION ALL SELECT 'The formation of new substances during a chemical reaction is accompanied by' AS q, 'a colour change only' AS a, 'a change in state only' AS b, 'a change in size' AS c, 'an energy change' AS d, 'D' AS k
    UNION ALL SELECT 'In a chemical reaction the total mass of products is equal to the total mass of the' AS q, 'catalyst' AS a, 'solvent' AS b, 'reactants' AS c, 'atmosphere' AS d, 'C' AS k
    UNION ALL SELECT 'This law states that matter is neither created nor destroyed in a chemical reaction. It is the law of' AS q, 'constant composition' AS a, 'conservation of mass' AS b, 'definite proportions' AS c, 'multiple proportions' AS d, 'B' AS k
    UNION ALL SELECT 'The law of constant composition states that a compound always contains the same' AS q, 'volume of gas' AS a, 'number of atoms' AS b, 'elements in the same proportion by mass' AS c, 'mass of catalyst' AS d, 'C' AS k
    UNION ALL SELECT 'A substance added to a chemical reaction to speed it up without being consumed is a' AS q, 'reagent' AS a, 'catalyst' AS b, 'product' AS c, 'solvent' AS d, 'B' AS k
    UNION ALL SELECT 'A substance that dissolves in a liquid to form a solution is the' AS q, 'solute' AS a, 'solvent' AS b, 'solution' AS c, 'suspension' AS d, 'A' AS k
    UNION ALL SELECT 'The liquid in a solution is called the' AS q, 'solute' AS a, 'colloid' AS b, 'solvent' AS c, 'suspension' AS d, 'C' AS k
    UNION ALL SELECT 'A solution in which the solute dissolves completely is described as' AS q, 'unsaturated' AS a, 'concentrated' AS b, 'saturated' AS c, 'dilute' AS d, 'C' AS k
    UNION ALL SELECT 'A solution that can dissolve no more solute at a given temperature is' AS q, 'immiscible' AS a, 'unsaturated' AS b, 'dilute' AS c, 'saturated' AS d, 'D' AS k
    UNION ALL SELECT 'A suspension is different from a solution because the particles of a suspension' AS q, 'never settle' AS a, 'are dissolved' AS b, 'are invisible' AS c, 'settle on standing' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is an example of a solution?' AS q, 'Oil in water' AS a, 'Chalk in water' AS b, 'Salt in water' AS c, 'Sand in water' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a heterogeneous mixture?' AS q, 'Salt in water' AS a, 'Sand in water' AS b, 'Sugar in water' AS c, 'Air' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a colloid?' AS q, 'Milk' AS a, 'Salt solution' AS b, 'Sugar solution' AS c, 'Mud' AS d, 'A' AS k
    UNION ALL SELECT 'The separation of an insoluble solid from a liquid is done by' AS q, 'evaporation' AS a, 'filteration' AS b, 'distillation' AS c, 'crystallisation' AS d, 'B' AS k
    UNION ALL SELECT 'The separation of a pure solid from a solution by heating is called' AS q, 'condensation' AS a, 'filteration' AS b, 'crystallisation' AS c, 'sublimation' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these separation methods is based on differences in boiling points?' AS q, 'Distillation' AS a, 'Filteration' AS b, 'Magnetic separation' AS c, 'Sieving' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is used to separate a mixture of common salt and water?' AS q, 'Crystallisation' AS a, 'Simple distillation' AS b, 'Magnetic separation' AS c, 'Filteration' AS d, 'A' AS k
    UNION ALL SELECT 'A separating funnel is used to separate two immiscible liquids of different' AS q, 'colours' AS a, 'boiling points' AS b, 'densities' AS c, 'solubilities' AS d, 'C' AS k
    UNION ALL SELECT 'The process of changing a gas directly into a liquid is called' AS q, 'sublimation' AS a, 'melting' AS b, 'deposition' AS c, 'condensation' AS d, 'D' AS k
    UNION ALL SELECT 'The process of changing a solid directly into a gas is called' AS q, 'condensation' AS a, 'sublimation' AS b, 'melting' AS c, 'evaporation' AS d, 'B' AS k
    UNION ALL SELECT 'The process of changing a liquid into a solid is called' AS q, 'evaporation' AS a, 'boiling' AS b, 'melting' AS c, 'freezing' AS d, 'D' AS k
    UNION ALL SELECT 'The change of state from liquid to gas is called' AS q, 'condensation' AS a, 'sublimation' AS b, 'freezing' AS c, 'evaporation' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is an example of sublimation?' AS q, 'Water boiling' AS a, 'Iron rusting' AS b, 'Camphor turning to vapour' AS c, 'Ice melting' AS d, 'C' AS k
    UNION ALL SELECT 'The boiling point of water is' AS q, '0 degrees celsius' AS a, '50 degrees celsius' AS b, '212 degrees celsius' AS c, '100 degrees celsius' AS d, 'D' AS k
    UNION ALL SELECT 'The melting point of ice is' AS q, '0 degrees celsius' AS a, '37 degrees celsius' AS b, '100 degrees celsius' AS c, '-100 degrees celsius' AS d, 'A' AS k
    UNION ALL SELECT 'Water is a universal solvent because it' AS q, 'is cheap' AS a, 'dissolves a large number of substances' AS b, 'is a liquid' AS c, 'is colourless' AS d, 'B' AS k
    UNION ALL SELECT 'The solubility of a substance is the maximum amount that dissolves in a given quantity of solvent at a given' AS q, 'concentration' AS a, 'pressure' AS b, 'volume' AS c, 'temperature' AS d, 'D' AS k
    UNION ALL SELECT 'The solubility of most solids in water increases as the' AS q, 'temperature increases' AS a, 'temperature decreases' AS b, 'pressure decreases' AS c, 'volume increases' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these factors does not affect the solubility of a solid in water?' AS q, 'Shape of the container' AS a, 'Nature of the solute' AS b, 'Nature of the solvent' AS c, 'Temperature' AS d, 'A' AS k
    UNION ALL SELECT 'A solution containing an equal amount of solute and solvent by mass is called' AS q, 'dilute' AS a, 'concentrated' AS b, 'saturated' AS c, 'molecular' AS d, 'B' AS k
    UNION ALL SELECT 'The strength of an acid depends mainly on the' AS q, 'amount of acid used' AS a, 'concentration of hydrogen ions' AS b, 'colour of the acid' AS c, 'container size' AS d, 'B' AS k
    UNION ALL SELECT 'An acid turns blue litmus paper' AS q, 'blue' AS a, 'red' AS b, 'green' AS c, 'orange' AS d, 'B' AS k
    UNION ALL SELECT 'A base turns red litmus paper' AS q, 'violet' AS a, 'blue' AS b, 'red' AS c, 'green' AS d, 'B' AS k
    UNION ALL SELECT 'What is the pH of a neutral solution at room temperature?' AS q, '0' AS a, '10' AS b, '14' AS c, '7' AS d, 'D' AS k
    UNION ALL SELECT 'What is the pH of a strongly acidic solution?' AS q, 'Above 7' AS a, 'Exactly 14' AS b, 'Below 7' AS c, 'Exactly 7' AS d, 'C' AS k
    UNION ALL SELECT 'What is the pH of a strongly alkaline solution?' AS q, 'Below 7' AS a, 'Exactly 7' AS b, 'Above 7' AS c, 'Exactly 0' AS d, 'C' AS k
    UNION ALL SELECT 'What happens to the pH of an acid when it is diluted with water?' AS q, 'It decreases' AS a, 'It increases' AS b, 'It stays the same' AS c, 'It becomes 7' AS d, 'B' AS k
    UNION ALL SELECT 'A solution of pH 3 is described as' AS q, 'alkaline' AS a, 'acidic' AS b, 'neutral' AS c, 'amphoteric' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these is a common alkali?' AS q, 'Nitric acid' AS a, 'Hydrochloric acid' AS b, 'Sodium hydroxide' AS c, 'Sulphuric acid' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is a mineral acid?' AS q, 'Hydrochloric acid' AS a, 'Sodium hydroxide' AS b, 'Ammonia solution' AS c, 'Calcium hydroxide' AS d, 'A' AS k
    UNION ALL SELECT 'Neutralisation is the reaction of an acid with a' AS q, 'salt' AS a, 'base' AS b, 'gas' AS c, 'metal' AS d, 'B' AS k
    UNION ALL SELECT 'The product of the neutralisation of a base with an acid is a' AS q, 'gas only' AS a, 'metal oxide only' AS b, 'alkali only' AS c, 'salt and water' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a common household acid?' AS q, 'Sodium hydroxide' AS a, 'Calcium hydroxide' AS b, 'Ammonia' AS c, 'Citric acid' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is a common use of alkalis?' AS q, 'Making soap' AS a, 'Fertilising crops' AS b, 'Making paper' AS c, 'All of the above' AS d, 'D' AS k
    UNION ALL SELECT 'A salt is formed when' AS q, 'all of the above' AS a, 'an acid reacts with a carbonate' AS b, 'an acid reacts with a base' AS c, 'an acid reacts with a metal' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is an acidic salt?' AS q, 'Sodium chloride' AS a, 'Ammonium nitrate' AS b, 'Calcium carbonate' AS c, 'Potassium hydroxide' AS d, 'B' AS k
    UNION ALL SELECT 'What kind of reaction occurs when zinc reacts with dilute hydrochloric acid?' AS q, 'Combination' AS a, 'Decomposition' AS b, 'Displacement' AS c, 'Neutralisation' AS d, 'C' AS k
    UNION ALL SELECT 'What kind of reaction occurs when hydrogen burns in oxygen?' AS q, 'Displacement' AS a, 'Decomposition' AS b, 'Neutralisation' AS c, 'Combination' AS d, 'D' AS k
    UNION ALL SELECT 'What kind of reaction occurs when calcium carbonate is heated strongly?' AS q, 'Combination' AS a, 'Decomposition' AS b, 'Displacement' AS c, 'Neutralisation' AS d, 'B' AS k
    UNION ALL SELECT 'Which of these reactions is a displacement reaction?' AS q, 'Magnesium plus oxygen forms magnesium oxide' AS a, 'Sodium plus water forms sodium hydroxide and hydrogen' AS b, 'Calcium carbonate forms calcium oxide and carbon dioxide' AS c, 'Hydrogen plus oxygen forms water' AS d, 'B' AS k
    UNION ALL SELECT 'A substance that speeds up a chemical reaction without being used up is a' AS q, 'reactant' AS a, 'solvent' AS b, 'product' AS c, 'catalyst' AS d, 'D' AS k
    UNION ALL SELECT 'The substance formed after a chemical reaction is the' AS q, 'product' AS a, 'reactant' AS b, 'catalyst' AS c, 'solvent' AS d, 'A' AS k
    UNION ALL SELECT 'The substance present before a chemical reaction is the' AS q, 'reactant' AS a, 'residue' AS b, 'catalyst' AS c, 'product' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these changes is a redox reaction?' AS q, 'Dissolution of sugar in water' AS a, 'Melting of ice' AS b, 'Breaking of glass' AS c, 'Combustion of magnesium' AS d, 'D' AS k
    UNION ALL SELECT 'During combustion, a substance reacts with' AS q, 'water' AS a, 'oxygen' AS b, 'carbon dioxide' AS c, 'nitrogen' AS d, 'B' AS k
    UNION ALL SELECT 'Complete combustion of a hydrocarbon produces' AS q, 'carbon dioxide and water' AS a, 'carbon monoxide and hydrogen' AS b, 'nitrogen and oxygen' AS c, 'water only' AS d, 'A' AS k
    UNION ALL SELECT 'The flame of burning magnesium is' AS q, 'bright white' AS a, 'invisible' AS b, 'blue' AS c, 'orange' AS d, 'A' AS k
    UNION ALL SELECT 'A common test for carbon dioxide gas is to bubble it through' AS q, 'starch solution' AS a, 'limewater' AS b, 'copper sulphate solution' AS c, 'silver nitrate solution' AS d, 'B' AS k
    UNION ALL SELECT 'Carbon dioxide turns limewater' AS q, 'white then milky' AS a, 'black' AS b, 'pink' AS c, 'blue' AS d, 'A' AS k
    UNION ALL SELECT 'Which gas turns limewater milky?' AS q, 'Carbon dioxide' AS a, 'Oxygen' AS b, 'Hydrogen' AS c, 'Nitrogen' AS d, 'A' AS k
    UNION ALL SELECT 'A common test for hydrogen gas is to bring a burning splint near it and it' AS q, 'burns with a pop sound' AS a, 'glows red' AS b, 'rekindles a glowing splint' AS c, 'turns limewater milky' AS d, 'A' AS k
    UNION ALL SELECT 'A burning splint rekindled in a gas identifies the gas as' AS q, 'oxygen' AS a, 'hydrogen' AS b, 'carbon dioxide' AS c, 'nitrogen' AS d, 'A' AS k
    UNION ALL SELECT 'Oxygen is needed for' AS q, 'digestion only' AS a, 'respiration only' AS b, 'combustion only' AS c, 'respiration and combustion' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these gases is most abundant in air?' AS q, 'Oxygen' AS a, 'Carbon dioxide' AS b, 'Nitrogen' AS c, 'Hydrogen' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is NOT a main component of air?' AS q, 'Hydrogen' AS a, 'Oxygen' AS b, 'Argon' AS c, 'Nitrogen' AS d, 'A' AS k
    UNION ALL SELECT 'Which gas is used in the Haber process to make ammonia?' AS q, 'Carbon dioxide' AS a, 'Hydrogen' AS b, 'Nitrogen' AS c, 'Oxygen' AS d, 'C' AS k
    UNION ALL SELECT 'Which gas is used in the manufacture of hydrochloric acid?' AS q, 'Oxygen' AS a, 'Chlorine' AS b, 'Hydrogen' AS c, 'Nitrogen' AS d, 'B' AS k
    UNION ALL SELECT 'Which gas is used to fill balloons?' AS q, 'Carbon dioxide' AS a, 'Hydrogen' AS b, 'Helium' AS c, 'Nitrogen' AS d, 'C' AS k
    UNION ALL SELECT 'What is the main gas responsible for the greenhouse effect?' AS q, 'Carbon dioxide' AS a, 'Hydrogen' AS b, 'Oxygen' AS c, 'Nitrogen' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these increases the concentration of carbon dioxide in the atmosphere?' AS q, 'Planting trees' AS a, 'Using solar energy' AS b, 'Recycling waste' AS c, 'Burning fossil fuels' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is NOT a chemical change?' AS q, 'Burning wood' AS a, 'Souring milk' AS b, 'Dissolving sugar in water' AS c, 'Rusting a nail' AS d, 'C' AS k
    UNION ALL SELECT 'A chemical reaction that releases heat to the surroundings is' AS q, 'endothermic' AS a, 'reversible' AS b, 'spontaneous' AS c, 'exothermic' AS d, 'D' AS k
    UNION ALL SELECT 'A chemical reaction that absorbs heat from the surroundings is' AS q, 'exothermic' AS a, 'complete' AS b, 'endothermic' AS c, 'combustion' AS d, 'C' AS k
    UNION ALL SELECT 'Which of these is an endothermic process?' AS q, 'Burning of a candle' AS a, 'Rusting of iron' AS b, 'Burning of wood' AS c, 'Melting of ice' AS d, 'D' AS k
    UNION ALL SELECT 'Which of these is an exothermic process?' AS q, 'Evaporation of water' AS a, 'Melting of ice' AS b, 'Dissolving ammonium nitrate' AS c, 'Burning of a candle' AS d, 'D' AS k
    UNION ALL SELECT 'What quantity of heat is required to raise the temperature of 1 kg of a substance by 1 degree celsius called?' AS q, 'Latent heat' AS a, 'Thermal capacity' AS b, 'Specific heat capacity' AS c, 'Molar heat' AS d, 'C' AS k
    UNION ALL SELECT 'The specific heat capacity of water is approximately' AS q, '4.2 joules per kilogram per degree celsius' AS a, '4200 kilojoules per kilogram per degree celsius' AS b, '0.24 joules per kilogram per degree celsius' AS c, '1 joule per kilogram per degree celsius' AS d, 'A' AS k
    UNION ALL SELECT 'Which metal has the highest specific heat capacity?' AS q, 'Iron' AS a, 'Aluminium' AS b, 'Copper' AS c, 'Lead' AS d, 'B' AS k
    UNION ALL SELECT 'Water has a high specific heat capacity which means that water' AS q, 'heats up quickly' AS a, 'heats up slowly and can store a lot of heat' AS b, 'does not absorb heat' AS c, 'loses heat instantly' AS d, 'B' AS k
    UNION ALL SELECT 'Heat is a form of' AS q, 'energy' AS a, 'power' AS b, 'force' AS c, 'matter' AS d, 'A' AS k
    UNION ALL SELECT 'The SI unit of heat is' AS q, 'degree celsius' AS a, 'calorie' AS b, 'kelvin' AS c, 'joule' AS d, 'D' AS k
    UNION ALL SELECT 'One calorie is equivalent to how many joules?' AS q, '4.2 J' AS a, '0.42 J' AS b, '42 J' AS c, '420 J' AS d, 'A' AS k
    UNION ALL SELECT 'What is the term for the direct transfer of heat from one body to another without a medium?' AS q, 'Radiation' AS a, 'Convection current' AS b, 'Conduction' AS c, 'Convection' AS d, 'C' AS k
    UNION ALL SELECT 'Metals are good conductors of heat because they have' AS q, 'free electrons' AS a, 'free protons' AS b, 'no electrons' AS c, 'high density' AS d, 'A' AS k
    UNION ALL SELECT 'Which of these is an alloy?' AS q, 'Pure copper' AS a, 'Pure iron' AS b, 'Brass' AS c, 'Pure gold' AS d, 'C' AS k
    UNION ALL SELECT 'Brass is an alloy of copper and' AS q, 'tin' AS a, 'zinc' AS b, 'lead' AS c, 'nickel' AS d, 'B' AS k
    UNION ALL SELECT 'Stainless steel is an alloy of iron and' AS q, 'zinc' AS a, 'carbon' AS b, 'chromium' AS c, 'copper' AS d, 'C' AS k
    UNION ALL SELECT 'Solder is an alloy of tin and' AS q, 'copper' AS a, 'zinc' AS b, 'aluminium' AS c, 'lead' AS d, 'D' AS k
    UNION ALL SELECT 'Type D cast iron contains the element' AS q, 'nickel' AS a, 'titanium' AS b, 'manganese' AS c, 'silicon' AS d, 'C' AS k
    UNION ALL SELECT 'An alloy is made by melting the constituents together because metals' AS q, 'cannot be mixed in the solid state' AS a, 'melt at the same temperature' AS b, 'dissolve only in acid' AS c, 'react chemically only when molten' AS d, 'D' AS k
  ) t ON 1 = 1
 WHERE s.subject_code = 'CHM201'
   AND NOT EXISTS (SELECT 1 FROM questions x WHERE x.subject_id = s.id);

-- ------------------------------------------------------------
-- Verification: expect 4 subjects and 497 questions.
-- Verification: expect 4 subjects and 497 questions.
SELECT s.subject_code, s.subject_name, COUNT(q.id) AS questions
  FROM subjects s
  LEFT JOIN questions q ON q.subject_id = s.id AND q.is_active = 1
 WHERE s.subject_code IN ('ENG201','MTH201','PHY201','CHM201')
 GROUP BY s.id, s.subject_code, s.subject_name
 ORDER BY s.subject_code;

SELECT COUNT(*) AS total_questions FROM questions;
